### ISSUE TITLE
level=error msg="Error scraping for BSM_Metrics _ map[transaction_id:Generic counter metric from v$resource_limit view in Oracle.] : No metrics found while parsing" source="main.go:235"

### ISSUE THREAD

**Issue by abhinavjj** [iamseth/oracledb_exporter#108]
Hi,

I'm using custom metric to collect my database information but when i start my oracledb_exporter im getting below error:

time="2020-06-17T17:58:14Z" level=info msg="Starting oracledb_exporter master" source="main.go:390"
time="2020-06-17T17:58:14Z" level=info msg="Successfully loaded default metrics from: default-metrics.toml" source="main.go:397"
time="2020-06-17T17:58:14Z" level=info msg="Successfully loaded custom metrics from: custom-metrics.toml" source="main.go:406"
time="2020-06-17T17:58:17Z" level=error msg="Error scraping for BSM_Metrics _ map[transaction_id:Generic counter metric from v$resource_limit view in Oracle.] : No metrics found while parsing" source="main.go:235"
time="2020-06-17T17:58:17Z" level=info msg="Listening on :9161" source="main.go:419"
time="2020-06-17T17:58:24Z" level=error msg="Error scraping for BSM_Metrics _ map[transaction_id:Generic counter metric from v$resource_limit view in Oracle.] : No metrics found while parsing" source="main.go:235"
time="2020-06-17T17:58:29Z" level=error msg="Error scraping for BSM_Metrics _ map[transaction_id:Generic counter metric from v$resource_limit view in Oracle.] : No metrics found while parsing" source="main.go:235"

 custom metrics.toml:

[[metric]]
context = "BSM_Metrics"
labels = [ "s.sample_datetime" ]
metricsdesc = { transaction_id= "Generic counter metric from v$resource_limit view in Oracle." }
request = "SELECT s.sample_datetime, l.location_name, t.transaction_name, st.status_name FROM SAMPLES s LEFT JOIN LOCATIONS l on s.location_id = l.location_id LEFT JOIN TRANSACTIONS t ON s.transaction_id = t.transaction_id LEFT JOIN STATUS_LIST st ON s.status = st.status_id WHERE s.sample_datetime >= sysdate - 2 and st.status_name = 'Fail'"

can someone pls suggest what's wrong with the metrics.toml ?

**Comment by Yannig** [comment]
Maybe you can provide an example of the result you get when you run this request:

```sql
SELECT
   s.sample_datetime as sample_datetime,
   l.location_name as location_name,
   t.transaction_name as transaction_name,
   st.status_name as status_name 
FROM
   SAMPLES s 
   LEFT JOIN
      LOCATIONS l 
      on s.location_id = l.location_id 
   LEFT JOIN
      TRANSACTIONS t 
      ON s.transaction_id = t.transaction_id 
   LEFT JOIN
      STATUS_LIST st 
      ON s.status = st.status_id 
WHERE
   s.sample_datetime >= sysdate - 2 
   and st.status_name = 'Fail'
```

From my point of view, there is already a problem with your request: there's no metrics that you sent back to Prometheus.
