### ISSUE TITLE
How to show the past data in the grafana

### ISSUE THREAD

**Issue by kim-tsai** [iamseth/oracledb_exporter#109]
HI
when I set a value in the metric, it only sample the first data in database. 
Our database have recorded the data with time information. 
How to sample the past data with time information?
example:
Our database:
data                time         value
2020/5/10	22:00:00	0
2020/5/10	22:00:00	0
2020/5/10	22:00:00	0
2020/5/10	22:00:00	0
2020/5/10	22:00:00	0
2020/5/9	        22:00:00	540
grafana show:
value : 0

**Comment by Yannig** [comment]
Sorry but I cannot answer your question:
- I dont know what you are talking about
- I dont have any example of what the exporter is sending back to prometheus
- I dont have any example of request on the Grafana

The aim of this project is to export values of Oracle not to do Grafana or Prometheus support.

**Comment by kim-tsai** [comment]
Hi
Thanks, for your answer
Sorry to mention this stupid question
Because we monitoring Oracle database based on prometheus and show the dashboard in grafana system
Your program is marked in prometheus (https://prometheus.io/docs/instrumenting/exporters/)
It makes me think like that.
Let me re-explain the problem
I want to find methods export oracle data with timestamp
Let oracle data match to prometheus time series data

**Comment by Yannig** [comment]
Prometheus handle directly the timestamps so you don't have to worry about it. You just have to export your values and let Prometheus do the dirty work. To get the value from the previous days, you can use an offset.

My advice is to export the raw value (for example the number of backup since database startup) without trying to transform them. You will be able to get informations using PromQL language. On the Oracle side, your query will be much more simplier.

You don't have any example of what you try to collect?

**Comment by Yannig** [comment]
A pointer to the offset: https://prometheus.io/docs/prometheus/latest/querying/basics/#offset-modifier

**Comment by kim-tsai** [comment]
Thanks, for your advice.
I try that it is works.
Prometheus records new data with timestamp
but it couldn't load my past data 
I already have the very more past data
I want to display them 
Now there are the data serialtime and the data value , but i don't know how to match they. 

First metric records value
[[metric]]
context = "TEST20200516"
request = "SELECT projnodeid as value FROM TEST20200516 WHERE tagname IN ('夜班總產量')"
metricsdesc = { value = "in Oracle." }

Second metric records time
[[metric]]
context = "TEST20200516"
request = "SELECT TO_NUMBER(TO_DATE(LOGDATE , 'YYYY-MM-DD HH24:MI:SS') - TO_DATE('1970-01-01 8:0:0', 'YYYY-MM-DD HH24:MI:SS')) * 24 * 60 * 60 as time FROM TEST20200516 WHERE tagname IN ('夜班總產量')"
metricsdesc = { time = "in Oracle." }

**Comment by Yannig** [comment]
Sorry being late to answer.

In fact, you cannot import previous data in Prometheus. Prometheus db is immutable. If you want the history, you have to wait and I dont know any way to "import" old data in Prometheus.

Sorry

**Comment by kim-tsai** [comment]
Thanks, for your answer.
I already get more benefit from your work.
Thank you.

**Comment by Yannig** [comment]
Fine, thanks your feedback.

So if you are ok with that, can we close this issue?

**Comment by kim-tsai** [comment]
Of course
