### ISSUE TITLE
Exporter HTTP handler hanging when exceeding 967 metrics

### ISSUE THREAD

**Issue by neilschelly** [iamseth/oracledb_exporter#111]
I've found that the exporter hangs if you are exporting too many metrics. To reproduce, I removed everything from the custom and default metrics, and put this as the only entry in the default metrics file.

```
[[metric]]
context = "integers"
labels = [ "value" ]
metricsdesc = { value= "Gauge metric integers counting up." }
request = '''
select value
from   dual
model
  dimension by ( 0 as key )
  measures     ( 0 as value )
  rules upsert ( value[ for key from 1 to 966 increment 1 ] = cv(key) )
'''
```

If you run the resulting container with something like `docker run -e DATA_SOURCE_NAME=username/password@//server:1521/database -p 9161:9161 iamseth/oracledb_exporter:alpine --log.level debug`, you will see it hang as it parses the query results at 966. Adding labels, even labels with lots of cardinality to the fake query doesn't change the number of metrics that work.

The Exporter container will continue to run and serve new requests, but the handler will just hang (blocked on a channel read) at this line: https://github.com/iamseth/oracledb_exporter/blob/master/main.go#L297
The HTTP request will never complete. If you drop that `966` in the above query to `960`, it will work fine. In between, it appears to lock up in a slightly different place in the Golang client library.

I was able to resolve this with an upgrade to the underlying Golang client library used for Prometheus metrics, but that was a more involved change involving switching from flags to kingpin for CLI arguments, switching from vendoring to Go modules, etc. I wanted to better document that process with an issue and submit a PR accordingly with these tests to prove what error I was seeing.

**Comment by Yannig** [comment]
Thanks for this contribution!
