### ISSUE TITLE
Multiple custom metrics

### ISSUE THREAD

**Issue by Hanoko** [iamseth/oracledb_exporter#113]
Hi,

Thanks for all the work on this project.

I would want to know if it is possible to use multiple custom metrics file. Or if it is possible to "import" another file into the configured one.

For example:
I have a multiple databases with 19c version but they are used by different applications. So If I want to add a metric for all 19c databases i wouldn't want to change all the files one by one. But I could add metrics for each application.

Thanks again!

**Comment by neilschelly** [comment]
Yes, you can put any queries you want into a custom-metrics file. The formatting of that file would be just like the formatting of the default-metrics.toml file in this repo.

**Comment by Hanoko** [comment]
I mean multiple files, not queries. Could that be possible?

**Comment by neilschelly** [comment]
Oh, I understand the question now. No, that's not currently possible. The code could certainly be modified to take a list of files treat them as one long concatenated file, I guess. The way it's coded now makes it easy to build a Docker container image based on this one with your custom metrics file placed  inside it. Doing that, you could build one that takes multiple files and concatenates them into a single file in the Docker image pretty easily.

**Comment by Yannig** [comment]
Hi @Hanoko, for the moment, this is not possible but it should be quite simple to handle this.

**Comment by Hanoko** [comment]
Hi Yannig, 

Do you think you could do the change? It would be awesome! I don't really have knowledge of Go, so it would be really hard for me to do the change. 

Thanks in advance.

**Comment by Yannig** [comment]
@Hanoko can you try to play with the exporter available in the multi-custom-metrics branch?

You can specify multiple files using the following example:

    oracledb_exporter -custom.metrics multi-metric-dual-example-labels.toml,metric-dual-example.toml

**Comment by Hanoko** [comment]
Awesome! Thanks! I will do some tests as soon as possible.

**Comment by Hanoko** [comment]
Hi Yannig,

I have done some tests compiling the docker image and it works perfect. Thanks for your awesome work.

**Comment by Yannig** [comment]
The main branch contains new features but it involves changes in the management of options.

As soon as I have a little time, I will prepare a version 0.3 with all these new features.

**Comment by Yannig** [comment]
Enhancement merged in master. Closing this.
