### ISSUE TITLE
Does oracledb_exporter support different ORACLE data types?

### ISSUE THREAD

**Issue by pebauer** [iamseth/oracledb_exporter#116]
Hi there,

I am using Prometheus (2.19.2) and Grafana (7.1.1). 

I have an ORACLE database table with thousands of lines, and the following structure:

| JOB_NAME  | START_TIMESTAMP | END_TIMESTAMP | DURATION_SEC | STATUS |
| ------------- | --------------------- | ------------------- | ----------------- | -------- |
| JOB_A    | 2020-07-30 00:27:55 | 2020-07-30 00:28:19 |           25 |      1 |
| JOB_B    | 2020-07-30 00:28:19 | 2020-07-30 00:30:21 |          122 |      1 |
| JOB_C    | 2020-07-30 00:30:42 | 2020-07-30 00:48:12 |         1051 |      1 |
| JOB_D    | 2020-07-30 02:58:02 | 2020-07-30 02:58:14 |           13 |      1 |
| JOB_E    | 2020-07-30 02:58:15 | 2020-07-30 02:58:20 |            5 |      1 |
| JOB_F    | 2020-07-30 02:58:20 | 2020-07-30 02:58:22 |            2 |      1 |
| JOB_G    | 2020-07-30 02:58:22 | 2020-07-30 02:58:23 |            1 |      1 |
| JOB_H    | 2020-07-30 02:58:23 | 2020-07-30 02:58:28 |            5 |      1 |
| JOB_I    | 2020-07-30 03:37:32 | 2020-07-30 03:37:33 |            1 |      1 |
| JOB_J    | 2020-07-30 03:37:33 | 2020-07-30 03:37:34 |            1 |      1 |
| ...    | ... | ... | ... | ... |

The columns of this table are of the following ORACLE data types:

| JOB_NAME  | START_TIMESTAMP | END_TIMESTAMP | DURATION_SEC | STATUS |
| ------------- | --------------------- | ------------------- | ----------------- | -------- |
| NVARCHAR2   | TIMESTAMP | TIMESTAMP | NUMBER | NUMBER |

I would like to monitor every job name's duration and status in Prometheus / Grafana.

In order to not manually maintain every single JOB_NAME (there are several thousands and they will change in future) in a separate PromQL query in one panel of Grafana, I would like to take a generic approach...

Grafana's Bar Gauge visualization (in the context of MySQL exporter) supports the possibility to generically repeat every column value of type string of a specific datatable column as display name (like in my case every JOB_NAME) and it's corresponding value (like in my case the DURATION_SEC or STATUS). 

See for more information [Bar Gauge : How to show Series name from a query’s row value (MySQL)](https://community.grafana.com/t/bar-gauge-how-to-show-series-name-from-a-querys-row-value-mysql/17809)

Does oracledb_exporter support different ORACLE data types like CHAR, NCHAR, VARCHAR, VARCHAR2, NVARCHAR2, TIMESTAMP, etc.? And if so, do I need to modify anything in my custom-metrics.toml file?

My DB query is the following and successfully leads to the expected output in ORACLE SQL Developer:
`SELECT`
`    JOB_NAME                                                            AS JOB_NAME,`
`    START_TIMESTAMP                                                     AS START_TIME,`
`    END_TIMESTAMP                                                       AS END_TIME,`
`    CEIL((TO_DATE(END_TIMESTAMP) - TO_DATE(START_TIMESTAMP))*24*60*60)  AS DURATION_SEC,`
`    CASE WHEN STATUS LIKE 'F' THEN 0 WHEN STATUS LIKE 'S' THEN 1 END    AS STATUS`
`FROM my_table`
`WHERE SUBSTR(START_TIMESTAMP, 1, 10) LIKE SUBSTR(SYSDATE, 1, 10)`

My custom metric would look like this:
`[[metric]]`
`context = "my_test_query"`
`labels = [ "job_name", "start_time", "end_time", "duration_sec", "status" ]`
`metricsdesc = { JOB_NAME="desc1", START_TIME="desc2", END_TIME="desc3", DURATION_SEC="desc4", STATUS="desc5" }`
`request = '''`
`SELECT `
`    JOB_NAME                                                            AS JOB_NAME,`
`    START_TIMESTAMP                                                     AS START_TIME,`
`    END_TIMESTAMP                                                       AS END_TIME,`
`    CEIL((TO_DATE(END_TIMESTAMP) - TO_DATE(START_TIMESTAMP))*24*60*60)  AS DURATION_SEC,`
`    CASE WHEN STATUS LIKE 'F' THEN 0 WHEN STATUS LIKE 'S' THEN 1 END    AS STATUS`
`FROM my_table`
`WHERE SUBSTR(START_TIMESTAMP, 1, 10) LIKE SUBSTR(SYSDATE, 1, 10)`
`'''`

Thanks for your help in advance!

**Comment by Yannig** [comment]
Hi,

In fact, Prometheus can only manage metrics and labels. Metrics can only be stored as float64 and labels are strings.

If you need to check job time, just add a job name label. You can then use PromQL to group things using request of this kind:

    max(job_time) by (job_name)

In Grafana, you will be able to access those labels
