### ISSUE TITLE
Example: How to use Oracle SID and tnsnames.ora

### ISSUE THREAD

**Issue by lunanigra** [iamseth/oracledb_exporter#119]
Can you please provide a full example "How to configure DB conection via Oracle SID".

```
# export Oracle location:
export DATA_SOURCE_NAME=system/password@oracle-sid
```
What is the best way to define the Oracle SID? Or where to store the tnsnames.ora file?

**Comment by josefoSe** [comment]
Hi ! I make a script in bash for linux, like start.sh and works for me. Maybe help:

#/bin/bash
export LD_LIBRARY_PATH=/usr/lib/oracle/19.6/client64/lib:$LD_LIBRARY_PATH
export DATA_SOURCE_NAME=user/password@server:1529/instance
./oracledb_exporter --log.level error --web.listen-address 0.0.0.0:9161

**Comment by lunanigra** [comment]
Ok, you can copy the file tnsnames.ora to /etc to get it working.
