### ISSUE TITLE
Can i point to multiple database with is exporter?

### ISSUE THREAD

**Issue by cazzprogrammer** [iamseth/oracledb_exporter#121]
Hi,

I want to point to multiple databases and scrape metrics from themusing this exporter. But in the environment variable "DATA SOURCE NAME" we can point to only one database as shown in the example code:

# export Oracle location:
export DATA_SOURCE_NAME=system/password@oracle-sid
# or using a complete url:
export DATA_SOURCE_NAME=user/password@//myhost:1521/service

Is there a way to do this?

thanks,
Dipankar.

**Comment by ChSanjayBabu** [comment]
I am aslo searchinga way pointing oracle_exporter to multiple databases, Hey @iamseth , @Yannig  can u pls help on this issue

**Comment by Yannig** [comment]
Hi,

There is no way to do that. Instead, run the exporter multiple time using different value for the DATA_SOURCE_NAME variable.

An easy way to do that is to use different docker container and map there respective port to different ports on the host machine.

**Comment by devopsusr-tech** [comment]
Hi @Yannig ,
is there any plan to implement such functionality?
It makes sense multiple databases running in a single host
