### ISSUE TITLE
Query period

### ISSUE THREAD

**Issue by kevinvirs** [iamseth/oracledb_exporter#122]
For heavy-weight queries set parameter query period. If query execute 1 or more minutes get error such as
`time="2020-08-13T03:29:24Z" level=error msg="Error scraping for tablespace _ map[bytes:Generic counter metric of tablespaces bytes in Oracle. free:Generic counter metric of tablespaces free bytes in Oracle. max_bytes:Generic counter metric of tablespaces max bytes in Oracle.] : Oracle query timed out" source="main.go:236"`

**Comment by Yannig** [comment]
You can set the query timeout using parameters or QUERY_TIMEOUT env variable.
If you do that, you will also need to change the scrape timeout value in Prometheus (https://prometheus.io/docs/prometheus/latest/configuration/configuration/)
