### ISSUE TITLE
Add oracle linux support

### ISSUE THREAD

**Issue by HenryXie1** [iamseth/oracledb_exporter#123]
Hi, there
  Recently I tested oracle Linux support on Makefile and Dockerfile. 
changes on Makefile is like
```
oraclelinux-image: $(ORA_RPM)
	docker build -f oraclelinux/Dockerfile $(BUILD_ARGS) -t "iamseth/oracledb_exporter:$(VERSION)-oraclelinux" .
	docker tag "iamseth/oracledb_exporter:$(VERSION)-oraclelinux" "iamseth/oracledb_exporter:oraclelinux"
```
 I would like to contribute it to the GitHub. Wonder how I can merge the changes?

Thank you

**Comment by Yannig** [comment]
No problem. You can create a PR :)
