### ISSUE TITLE
Oracle query timed out

### ISSUE THREAD

**Issue by jschin** [iamseth/oracledb_exporter#126]
hi 

I am running Pre-compiled versions for Linux 64 bit. but I having Oracle query timed out when the exporter trying to scrape tablespaces info. 

Below is the error log: 

anyway to increase the timeout ? 

`Error scraping for tablespace _ map[bytes:Generic counter metric of tablespaces bytes in Oracle. free:Generic counter metric of tablespaces free bytes in Oracle. max_bytes:Generic counter metric of tablespaces max bytes in Oracle.] : Oracle query timed out  source=main.go:235`

**Comment by Yannig** [comment]
The master version of the exporter have a new tablespace query. Can you try to use it?

https://github.com/iamseth/oracledb_exporter/blob/master/default-metrics.toml

**Comment by jan2ary** [comment]
Hi,
Oracle has some issues querying tablespace info with suboptimal plan. It is recommended to gather fixed object statistics on the database level, e.g. connect with dba privileges and exec dbms_stats.gather_fixed_objects_stats.

**Comment by Yannig** [comment]
@jan2ary Thank you for this remark, but I don't really see what that implies: should you plan to launch an Oracle job at regular intervals?

Could you give us an example (even a quick one) to understand what it would take to make the exporter work properly / faster with your instructions?

**Comment by jan2ary** [comment]
Hmmm, just double checked query in current exporter installation - 0.2.9-alpine, and it has old query with "Z.name as tablespace" and it times out. The new query from current default-metrics.yml works fine, although with remark that I have tried it from sqlplus only, not from binary exporter. My comment was about old query and is no longer relevant.

**Comment by Yannig** [comment]
Ok thanks. So closing then.
