### ISSUE TITLE
ignorezeroresult = true, not working

### ISSUE THREAD

**Issue by wongster80** [iamseth/oracledb_exporter#127]
Hi 
I want to monitor invalid objects but the query i have when there are not any "invalid" objects, returns no rows.
Using the ignorezeroresult = true 
[[metric]]
context = "invalid_objects"
labels = [ "owner", "object_type" ]
metricsdesc = { value="Gauge metric listing invalid objects, owner and object type." }
request = "SELECT owner, object_type, count(*) as value FROM all_objects WHERE status = 'INVALID' GROUP BY owner, object_type"
ignorezeroresult = true

I would get this error
Sep  1 07:53:32 odb1 oracledb_exporter: time="2020-09-01T07:53:32Z" level=error msg="Error scraping for invalid_objects _ map[value:Gauge metric listing invalid objects, owner and object type .] : sql: expected 1 arguments, got 0" source="main.go:235"

Any way I an still make the exporter return something when no rows are return?

**Comment by Yannig** [comment]
Hi,

Thanks for your report.

Maybe you can remove the WHERE statement, move the status to the labels and rename your context to object_status. This way, you will always get something back and you can have informations about all kind of status.

I agree, this is a work around for your problem. The ignorezeroresult is here to avoid this kind of message. I'll try to reproduce this issue on my side.

**Comment by ishantanu** [comment]
Hi, I am facing an issue while reporting metrics for queries which don't return anything and I think it might be related to `ignorezeroresult = true`. Here's what I am seeing in the logs:

```
time="2020-09-28T12:50:44Z" level=debug msg="About to scrape metric: " source="main.go:215"
time="2020-09-28T12:50:44Z" level=debug msg="- Metric MetricsDesc:  map[ab_batch:Batch count when CD_STATUS was aborted]" source="main.go:216"
time="2020-09-28T12:50:44Z" level=debug msg="- Metric Context:  aborted_batch" source="main.go:217"
time="2020-09-28T12:50:44Z" level=debug msg="- Metric MetricsType:  map[]" source="main.go:218"
time="2020-09-28T12:50:44Z" level=debug msg="- Metric Labels:  [ab_batch cd_status]" source="main.go:219"
time="2020-09-28T12:50:44Z" level=debug msg="- Metric FieldToAppend:  " source="main.go:220"
time="2020-09-28T12:50:44Z" level=debug msg="- Metric IgnoreZeroResult:  true" source="main.go:221"
time="2020-09-28T12:50:44Z" level=debug msg="- Metric Request:  SELECT AB_BATCH FROM XYZ WHERE CD_STATUS='aborted'" source="main.go:222"
time="2020-09-28T12:50:44Z" level=debug msg="Calling function ScrapeGenericValues()" source="main.go:263"
time="2020-09-28T12:50:46Z" level=debug msg="ScrapeGenericValues() - metricsCount:  0" source="main.go:312"
time="2020-09-28T12:50:46Z" level=debug msg="Successfully scrapped metric:  aborted_batch" source="main.go:238"

```

As you can see, no error is being reported but I am not seeing any metric reported for this sql query either. I know there is no `AB_BATCH` at the moment with `aborted` status but I still want to return the value of this metric as zero. And when there are aborted batch, I want to return the details. How can I achieve this? This is my custom metrics file:


```
    [[metric]]
    context = "aborted_batch"
    labels = ["ab_batch", "cd_status"]
    request = "SELECT AB_BATCH FROM XYZ WHERE CD_STATUS='aborted'"
    metricsdesc = { pb_batch = "Batch number when CD_STATUS was aborted" }
    ignorezeroresult = true
```

**Comment by Yannig** [comment]
From my point of view, this is on purpose. If nothing is returned from the query, there will be no metrics present. If you want something, you need another indicator that counts the number of results returned.

Here the query would surely be something like this:

```sql
select count (ab_batch) from xyz where foo = 'bar'
```

**Comment by ishantanu** [comment]
Okay. So, I tried the query you suggested. That worked. But, I was looking for returning ab_batch (a numeric field) where the cd_status was aborted. And that, somehow, is not working. Perhaps I am missing out on something to get this result? Great work on the exporter though. :+1:

**Comment by Yannig** [comment]
In prometheus, you can use a query to check if the metric is absent:

   absent(nonexistent{job="myjob"})

You can also use a query to sum all metrics of a given name. If the result is zero, everything is fine and if not, there's something wrong.

You can also have to separate queries: one for the count and the other to have details.

**Comment by ishantanu** [comment]
Got it. Thanks.
