### ISSUE TITLE
请问有支持oracle11g的oracledb_exporter版本吗

### ISSUE THREAD

**Issue by johnny14889** [iamseth/oracledb_exporter#128]
请问有支持oracle11g的oracledb_exporter版本吗

**Comment by johnny14889** [comment]
1

**Comment by jwh5566** [comment]
we also has oracle 11g  and I use the oracledb_exporter latest  version， but the docker log has error    ex：

Error pinging oracle: ORA-01017: invalid username/password; logon denied\n" source="main.go:215"

is the oracle version result in this problem ？？？  thanks a lot
