### ISSUE TITLE
Bug: Compiling error: continue is not in a loop

### ISSUE THREAD

**Issue by daviddetorres** [iamseth/oracledb_exporter#130]
I'm having this compiling errors while building the Docker image: 
```
./main.go:236:5: continue is not in a loop
./main.go:241:5: continue is not in a loop
```
It seems that the problem is here:
https://github.com/iamseth/oracledb_exporter/blob/6f6b77414635b0e9ef99fe94c9c2f5cf711186b9/main.go#L236
https://github.com/iamseth/oracledb_exporter/blob/6f6b77414635b0e9ef99fe94c9c2f5cf711186b9/main.go#L241

**Comment by Pilo11** [comment]
Yes, the same is listed in the latest build log "https://travis-ci.org/github/iamseth/oracledb_exporter".

I'd suggest to replace continue by return...

**Comment by Yannig** [comment]
Thanks for the report.
Fix in master branch
