### ISSUE TITLE
Attribution in PromCat repo and adding file with custom metrics examples

### ISSUE THREAD

**Issue by daviddetorres** [iamseth/oracledb_exporter#132]
Hi, 

In the [repository of PromCat](https://github.com/sysdiglabs/promcat-resources) (Prometheus Catalog) we included the integration of Oracle DB and [referenced the Oracle Exporter](https://github.com/sysdiglabs/promcat-resources/blob/staging/resources/oracle-db/README.md) with its license and attribution. You can check if it is ok. If you want to add further information on the attribution, you can contact us or directly send a PR with the correct information. 

Also, we created some configurations, adding a file with some custom metrics for slow queries, big queries and big tables. You can find it [here](https://github.com/sysdiglabs/promcat-resources/blob/216802cb3c30a64efbe1ba5772374ecefb00c1ed/resources/oracle-db/include/oracle-db-deployment.yaml#L121). 

We can make a PR to add the file with these custom queries to this repository if you think it is ok.

**Comment by Yannig** [comment]
Hi,

Thanks @daviddetorres !

Just a note: you are talking about version 12.1 for the database. Actually, the scrapper is compiled with more recent binaries (18.5) and you can monitor any type of base between 11g and the latest versions of Oracle.

Regards,

**Comment by daviddetorres** [comment]
That seems great! We will test that the metrics maintain the names and labels for the dashboards and alerts and that the custom queries still work in `19.3.0.0` and document the compatibility. 

What about the custom queries file? Are you interested in adding it to your documentation? Should we make a PR? If so, where do you think it is the correct place to add it?

**Comment by Yannig** [comment]
Yes of course! PR are welcome!

Maybe you can put this custom queries into a new directory (custom-metrics-example/?) and refer them in the README.

**Comment by Yannig** [comment]
PR is merged. Closing
https://github.com/iamseth/oracledb_exporter/pull/137
