### ISSUE TITLE
How can we configure oracledb_exporter to work for Oracle DB server 19.0.0/lib/libclntsh.so.19.1

### ISSUE THREAD

**Issue by spbangalore** [iamseth/oracledb_exporter#140]
Hi,

We were trying to configure oracledb_exporter to work for Oracle DB server 19.0.0/lib/libclntsh.so.19.1.
However getting error "Error while loading shared libraries: libclntsh.so.18.1:cannot open shared object file: Ni such file or directory"
Also, is this exporter is only for 18.1 or below DB version?

Note :- we are trying this on DB server and we do not have any client there (as its DB server only).
![Error libclntsh_so](https://user-images.githubusercontent.com/45715256/93734470-ede5ac00-fbf6-11ea-973d-9996e05f87a5.JPG)

**Comment by Yannig** [comment]
You can create a symlink. That should be enough to start the exporter.
My point of view on this subject is to use a Docker image. This way you dont have to worry about the dependencies.

**Comment by Yannig** [comment]
And also, please, please, before creating an issue for that, could you please read the troubleshooting section.

```
error while loading shared libraries: libclntsh.so.xx.x: cannot open shared object file: No such file or directory

This exporter use libs from Oracle in order to connect to Oracle Database. If you are running the binary version, you must install the Oracle binaries somewhere on your machine and you must install the good version number. If the error talk about the version 18.3, you must install 18.3 binary version. If it's 12.2, you must install 12.2.

An alternative is to run this exporter using a Docker container. This way, you don't have to worry about Oracle binaries version as they are embedded in the container.

Here an example to run this exporter (to scrap metrics from system/oracle@//host:1521/service-or-sid) and bind the exporter port (9161) to the global machine:

docker run -it --rm -p 9161:9161 -e DATA_SOURCE_NAME=system/oracle@//host:1521/service-or-sid iamseth/oracledb_exporter:0.2.6a
```

**Comment by spbangalore** [comment]
> You can create a symlink. That should be enough to start the exporter.
> My point of view on this subject is to use a Docker image. This way you dont have to worry about the dependencies.

Thnak you Yannig, I have already tried symbolic link and it was not working. I will check with the team using docker image. You are right with this we can remove dependencies.
