### ISSUE TITLE
Oracle query timed out

### ISSUE THREAD

**Issue by aleksandarilic96** [iamseth/oracledb_exporter#143]
Hello,

I have been running a couple of queries on my DB and for some of them I have been getting an error Oracle query timed out" source="main.go:256

One question looking through the past issues I can see a mention of queryTimeout parameter. Is this something that is implemented and can it be passed through the same way as custommetrics 

ENTRYPOINT ["/oracledb_exporter", "--queryTimeout ", "10"]

If not is there any other way to configure this?

Thanks and Best Regards

**Comment by pnrmx** [comment]
You can define environment variable `QUERY_TIMEOUT 10` for example. It is time in seconds for exporter waiting query.

**Comment by aleksandarilic96** [comment]
Im not sure where would i set that variable inside of toml file or?

**Comment by Yannig** [comment]
You cannot set it directly in toml file. You need to set it before running the exporter. Here an example:

    $ export QUERY_TIMEOUT=10
    $ export DATA_SOURCE_NAME=my/credentials@//myhost:port/sid-or-service-name
    $ ./oracledb_exporter
