### ISSUE TITLE
What is the expected form of the DATA_SOURCE_NAME string?

### ISSUE THREAD

**Issue by zjsen668** [iamseth/oracledb_exporter#15]
Hi,
    I defined the environment DATA_SOURCE_NAME with username/password@10.1.0.228:1521/xe，and run it in container, but I got error like this:
`level=error msg="Error pinging oracle: can't OCIEnvCreate" source="main.go:136" `
I guess the DATA_SOURCE_NAME was not in correct form, could you please correct me?

I can connect to my database with the following tns description string:
`(DESCRIPTION =
    (ADDRESS = (PROTOCOL = TCP)(HOST = 10.1.0.228)(PORT = 1521))
    (CONNECT_DATA =(SERVER = DEDICATED)(SID = xe))
)`

**Comment by iamseth** [comment]
It should be the same as the SQLPlus [EZConnect](http://www.orafaq.com/wiki/EZCONNECT) syntax.

```USERNAME/PASSWORD@//HOSTNAME:PORT/SERVICE_NAME```

If your username or password have any special characters, be sure to quote them. A '@' or '$' for example may be interpreted by the shell.

**Comment by zjsen668** [comment]
@iamseth 
Thanks for your reply！ 
I have tried again according to what you said, but still got error。In addition, my username and password have no special characters, and, I can connect the database properly using sqlplus .
![3321](https://user-images.githubusercontent.com/16451999/33539007-2d60fba0-d8ff-11e7-8296-255e0eaa545f.png)

**Comment by zjsen668** [comment]
@iamseth
How can I get more details of the error message?

**Comment by iamseth** [comment]
It looks like the library used doesn't get an error from Oracle. Here's the place where that error is coming from. https://github.com/mattn/go-oci8/blob/master/oci8.go#L709-L716

Maybe Oracle itself might log something. If the connection isn't encrypted, you might try a tcpdump to see if any error is passed over the wire.

**Comment by zjsen668** [comment]
I still haven't got expected result, but thank you very much。
I can't find any connection info in oracle server's log files (there are others).
I did the test following this step，but the result is the same.
`docker run --name oracle -d -p 8080:8080 -p 1521:1521 sath89/oracle-12c
docker run -d --link=oracle -p 9161:9161 -e DATA_SOURCE_NAME=system/oracle@oracle/xe.oracle.docker iamseth/oracledb_exporter`

**Comment by iamseth** [comment]
This is my fault. I caused a regression in the Docker image when I was trying to get the size down by removing packages. I'm not sure how I missed it but my apologies.

Please try the following. I did change the image used for Oracle just because the old one was taking a long time to start fully for me.

```bash
docker run -d --name oracle -p 1521:1521 wnameless/oracle-xe-11g:16.04
docker run -d --name oracledb_exporter --link=oracle -p 9161:9161 -e DATA_SOURCE_NAME=system/oracle@oracle/xe iamseth/oracledb_exporter:0.0.5
```

**Comment by zjsen668** [comment]
Great! That's it! Thanks a lot!
