### ISSUE TITLE
How to set the interval between query's being reexecuted

### ISSUE THREAD

**Issue by osbornj6** [iamseth/oracledb_exporter#152]
Whilst I've successfully managed to get this working with my own TOML file and connecting to an existing Oracle DB, I don't know how it might be possible to configure the interval that controls how often the queries are executed.  They appear to execute on a per 15 second basis, but wondered if this is configured by a parameter at all.

**Comment by Yannig** [comment]
The scraping interval is set directly in Prometheus. You can follow this link to understand to modify this:

https://prometheus.io/docs/prometheus/latest/configuration/configuration/
