### ISSUE TITLE
Bug - Many sessions present

### ISSUE THREAD

**Issue by jjabinx** [iamseth/oracledb_exporter#155]
Hello everyone!

I've recently added the exporter to monitor one of my databases, and I've had some odd problem happen.
I've created a special user for the exporter to use (which only it uses) and opened the exporter with default values (so according to main.go the maximum number of sessions should be 10)
However when checking out the v$session table on the database after a few days, there are 42 sessions for the user used only by the exporter (in the first day or so only 1 session was present)

Any idea why this might happen? This is using a significant number of resources for a database that is already under heavy use.

Thank you!

**Comment by Yannig** [comment]
Hi,

I'm not sure where it could come from. You could tell more about the version you are using at the exporter level as well as the database, system etc.

Regards,

**Comment by jjabinx** [comment]
Hi there! Sorry for the delay in the response.
I'm using version 0.2.2 of the exporter on docker, and it connects to 12c.
For some reason when I query v$session I see much more than 10 sessions for the exporter even after killing all its sessions multiple times. All sessions seem to be in the INACTIVE state, all opened over the last 5 days or so (since I last killed them)
Is there maybe some problem with closing connections correctly on error or in general?

Thanks again for the help!

**Comment by Yannig** [comment]
Well, that's a very old version!

There has been quite a bit of patch on the connection to the database or driver updates. You should definitely try a newer version.
