### ISSUE TITLE
muktiple instances on one sever

### ISSUE THREAD

**Issue by trondk** [iamseth/oracledb_exporter#161]
i have multible oracle servers running on one host.
is there a way to use the exporter on that .
/T

**Comment by Yannig** [comment]
Nop, you need to run the exporter several times. Each instance (aka SID) must have a separate exporter.
You can run the exporter using several different port

**Comment by trondk** [comment]
> Nop, you need to run the exporter several times. Each instance (aka SID) must have a separate exporter.
> You can run the exporter using several different port

ok, i through that this will be the case, I'm writing some facts to puppet, so i can auto install the exporter(s), as needed.
this will take some time
but thanks for the help, and the nice exporter. :-)

**Comment by Yannig** [comment]
Thanks :)
