### ISSUE TITLE
I can't use the oracle_exporter

### ISSUE THREAD

**Issue by chabater** [iamseth/oracledb_exporter#166]
I have same issue in https://github.com/iamseth/oracledb_exporter/issues/61 on oracle version 1.12
I try to link libclntsh.so.18.1 to /ora_sys/app/db12c/lib/libclntsh.so.18.1 , but it still error on oracledb_exporter[66102] : /root/oracledb_exporter.0.2.9-ora18.5.linux-amd64/oracledb_exporter: error while loading shared libraries: libclntsh.so.18.1: cannot open shared object file: No such file or directory

**Comment by Yannig** [comment]
Sorry but you have to set the ORACLE_HOME and LD_LIBRARY_PATH.

Here is an example with the more important values taken from the system D integration:

``` bash
export DATA_SOURCE_NAME="dbsnmp/Bercut01@//primaryhost:1521,standbyhost:1521/myservice"
export LD_LIBRARY_PATH="/u01/app/oracle/product/19.0.0/dbhome_1/lib"
export ORACLE_HOME="/u01/app/oracle/product/19.0.0/dbhome_1"
export CUSTOM_METRICS="/etc/oracledb_exporter/custom-metrics.toml"
```
