### ISSUE TITLE
 安装步骤描述错误 Installation step description error

### ISSUE THREAD

**Issue by ZheErMao** [iamseth/oracledb_exporter#170]
Installation step description error

See figure
![image](https://user-images.githubusercontent.com/6259419/110271053-37d61900-8002-11eb-8f4e-a012dd326bf4.png)

**Comment by mrjimroll** [comment]
Fixed in PR #173  ;  waiting for approve

**Comment by Yannig** [comment]
Fix in master. Thanks @mrjimroll !
