### ISSUE TITLE
How to provide the username and password in systemd encrypted and not plain text

### ISSUE THREAD

**Issue by skiransk** [iamseth/oracledb_exporter#175]
Hi @iamseth @Yannig , 

Can you please navigate me to right process. I am able to connect to the DB by providing the username and password in the systemd file as mentioned below. But, I do not want to provide in plain text. So is there any other option to provide the password in the .service file encrypted. 

export DATA_SOURCE_NAME=user/password@//myhost:1521/service

**Comment by Yannig** [comment]
Hi,

There is no way to do that for the moment. As a workaround you can try to add the the user in the oracle group and connect directly as sysdba. In fact, I don't know if it's working or not. There is already an issue with everything described at the following location: https://github.com/iamseth/oracledb_exporter/issues/48

The PR needed in the OCI driver seems to be merged. So maybe it's working or maybe not ...

If you want to use a regular user, in fact there's no way to encrypt the passwor. You can also use a separate file with the credentials inside.
