### ISSUE TITLE
error while loading shared libraries: libclntsh.so.xx.x

### ISSUE THREAD

**Issue by LuccasRamos** [iamseth/oracledb_exporter#192]
Hello gentlemen.

After receiving the error:
/usr/local/bin/oracledb_exporter: error while loading shared libraries: libclntsh.so.18.1: cannot open shared object file: No such file or directory

I read the "FAQ/Troubleshooting" section. As a DBA, I understand that it is not necessary to run a docker or install a client in the specified version, since oracle provides the necessary libs, pointing with a symbolic link to a file of the specified version.

so, just setting the variable "LD_LIBRARY_PATH" could be the solution, but I still have this error.
<img width="596" alt="Screen Shot 2021-07-15 at 17 34 46" src="https://user-images.githubusercontent.com/5496073/125854680-dd8db6e3-5271-40f1-84ff-d29a1be1de77.png">

**Comment by voskampm** [comment]
Please take a look at https://github.com/iamseth/oracledb_exporter#error-while-loading-shared-libraries-libclntshsoxxx-cannot-open-shared-object-file-no-such-file-or-directory.  Your binary seems to be compiled against Oracle 18.1 but you have installed Oracle 19.1. Recompile your binary against Oracle 19.1 or install Oracle 18.1 client.
