### ISSUE TITLE
High CPU consumption, generating load

### ISSUE THREAD

**Issue by DgoNascimento** [iamseth/oracledb_exporter#193]
Good afternoon people,

I would like your help regarding the CPU usage by the oracledb_exporter agent.

We have 15 databases (exadata) in the environment that we must monitor. Thus, we decided to install agents to collect information remotely on the server used by Oracle Enterprise Manager.

We created 15 different services, so that we have each connection with your bank, in addition to exposing on different ports.

The fact is that oracledb_exporter consumes a lot of server CPU, generating load.

We only left 6 services in the air, but still we have a high consumption of resources.

I take this opportunity for a doubt. Is the consumption of the process related to the collection of prometheus (in the configured url and port)?

Thank you in advance.

**Comment by DgoNascimento** [comment]
@iamseth, Could you support with this problem? Thank you so much

**Comment by Yannig** [comment]
To be honest, I don't know anything about your setup. I advise you to approach an Oracle administrator and determine with him which requests consume resources. If necessary, do not hesitate to deactivate requests that could pose a problem.
