### ISSUE TITLE
Required clarification regarding User and Group in oracledb_exporter.service file.

### ISSUE THREAD

**Issue by chvvnsaisurya** [iamseth/oracledb_exporter#199]
Please tell me regarding the User and Group in oracledb_exporter.service file.

In this info "Create oracledb_exporter user with disabled login and oracledb_exporter group", please tell how can i create oracledb_exporter user with disabled login and oracledb_exporter group?

**Comment by Yannig** [comment]
https://letmegooglethat.com/?q=Create+user+with+disabled+login
