### ISSUE TITLE
Please add FRA limit and  used

### ISSUE THREAD

**Issue by samueletonon** [iamseth/oracledb_exporter#20]
Not really an issue but more a feature request with something already implemented but not working.
[patch.txt](https://github.com/iamseth/oracledb_exporter/files/1763090/patch.txt)

In short: it would be nice to have space_limit and space_used information of a FRA of an oracle db.

The query you see in the patch is working from sqlplus, but if i compile and launch oracledb_exporter i get

ERRO[0000] Error scraping for FRA space: OCI_SUCCESS_WITH_INFO  source=main.go:

which is kind of odd and i don't know how to debug it.
It would be nice to have FRA information in the exporter, if you find a way to include it in the code it would be awesome

**Comment by iamseth** [comment]
Sure, I can add this.

I'm not familiar with[ v$recovery_file_dest](https://docs.oracle.com/cd/B12037_01/server.101/b10755/dynviews_2034.htm). Is it possible for that query to return 2+ results?

**Comment by samueletonon** [comment]
In my user cases it always return one line - therefore the use of QueryRow instead of Query . 

I do not know of installations with multiple FRA, but the world is  big and "diverse" . 
i also tried an implementation with Query - just in case there were cases where it was returning more than one row -  but the code was never going inside the block

for row.Next() { 

but my golang is rather poor. i can test for you different implementation .

**Comment by iamseth** [comment]
Having the same problem myself. I'm pretty busy this month with OSCP labs but I can take a better look after.

**Comment by nqirod** [comment]
I have writed something about this in my fork on this repo, only the percentage used but it still usable ;)

**Comment by samueletonon** [comment]
sorry @nqirod, having same problem with your solution for FRA, tried also RMAN scrape both with no success

**Comment by samueletonon** [comment]
it looks like it is something related to oci way of handling errors

**Comment by samueletonon** [comment]
Hello, does this means you have no plans of adding metrics on FRA ?

**Comment by T-M-A** [comment]
Hello! 

if I use another driver, then all of the samples from this view work. 

[Sample](https://gist.github.com/T-M-A/5ee1f4a087319e5ad9f57dc3bace13de)
