### ISSUE TITLE
Facing errors in running oracledb_exporter.service.

### ISSUE THREAD

**Issue by chvvnsaisurya** [iamseth/oracledb_exporter#200]
below is the status when i run the oracledb_exporter.service, Please help in solving this issue.

● oracledb_exporter.service - Service for oracle telemetry client
   Loaded: loaded (/etc/systemd/system/oracledb_exporter.service; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2021-08-06 12:48:44 IST; 3s ago
  Process: 25630 ExecStart=/usr/local/bin/oracledb_exporter --default.metrics /etc/oracledb_exporter/default-metrics.toml --log.level error --web.list
 Main PID: 25630 (code=exited, status=1/FAILURE)

 systemd[1]: Starting Service for oracle telemetry client...
 oracledb_exporter[25630]: time="2021-08-06T12:48:44+05:30" level=error msg="Error pinging oracle: ORA-12154: TNS:could not r
 oracledb_exporter[25630]: time="2021-08-06T12:48:44+05:30" level=fatal msg="listen tcp 0.0.0.0:9161: bind: address already i
systemd[1]: oracledb_exporter.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: oracledb_exporter.service: Failed with result 'exit-code'.
systemd[1]: Failed to start Service for oracle telemetry client.

**Comment by chvvnsaisurya** [comment]
here is the oracledb_exporter.service file

[Unit]
Description=Service for oracle telemetry client
After=network.target
[Service]
Type=oneshot
#!!! Set your values and uncomment
User=sys as sysdba
#Group=oracledb_exporter
Environment="DATA_SOURCE_NAME=sys as sysdba/oracle@//myhost:1521/XE"
Environment="LD_LIBRARY_PATH=/usr/lib/oracle/21/client64/lib"
Environment="ORACLE_HOME=/usr/lib/oracle/21/client64"
#Environment="CUSTOM_METRICS=/etc/oracledb_exporter/custom-metrics.toml"
ExecStart=/usr/local/bin/oracledb_exporter  \
  --default.metrics "/etc/oracledb_exporter/default-metrics.toml"  \
  --log.level error --web.listen-address 0.0.0.0:9161
[Install]
WantedBy=multi-user.target

**Comment by grayson85** [comment]
Your port 9161 has been used by other application.
