### ISSUE TITLE
Reduce number of vulnerabilities (ubuntu18.x=>20.x); There is a problem when using --log.level=debug make a credential leakage into logs

### ISSUE THREAD

**Issue by vutkin** [iamseth/oracledb_exporter#205]
* Need to reduce a number of vulnerabilities:
Current image
![image](https://user-images.githubusercontent.com/25753488/133221860-ac632a80-d5e3-4186-a14e-b73c07f79362.png)
New image:
![image](https://user-images.githubusercontent.com/25753488/133222027-721097b6-bd47-4f83-8c0f-bf74395045a6.png)
* Switch to non-root container
* There is a problem when using --log.level=debug make a credential leakage into logs.

**Comment by vutkin** [comment]
PR: https://github.com/iamseth/oracledb_exporter/pull/204

**Comment by vutkin** [comment]
@Yannig Could you please advise how to create a new docker images release?

**Comment by Yannig** [comment]
There is a problem with the current builder (Travis). I think it's a good time to create a new org for this project and move everything to a different place.

For the moment, I have pushed the image on my Docker registry. You can retrieve the image here:

    docker pull yannig/oracledb_exporter:0.3.2
