### ISSUE TITLE
I build the exporter in the windows，and how can i connect the Oracle database

### ISSUE THREAD

**Issue by zhongmin2015** [iamseth/oracledb_exporter#217]

**Comment by zhongmin2015** [comment]
INFO[0000] Starting oracledb_exporter 0.0.0.dev          source="main.go:553"
INFO[0000] Successfully loaded default metrics from: default-metrics.toml  source="main.go:528"
INFO[0000] No custom metrics defined.                    source="main.go:543"
ERRO[0000] Error pinging oracle: empty dsn               source="main.go:224"
INFO[0000] Listening on :9161                            source="main.go:589"

**Comment by Yannig** [comment]
There's a README at the root of this repository. You can read it. Everything is explained inside.
