### ISSUE TITLE
Scraping error with wait_time metrics

### ISSUE THREAD

**Issue by nqirod** [iamseth/oracledb_exporter#22]
Hello,

`Error scraping for wait_time: sql: Scan error on column index 1: converting driver.Value type string (",01") to a float64: invalid syntax  source="main.go:144"`

I have also the same problem with any metrics returned in float64 from a sql request, did you know how to fix it ? Thx in advance

**Comment by iamseth** [comment]
That's odd that the value is returning ",01".

What do you get if you run this query manually?


`SELECT name, value FROM v$sysstat WHERE name IN ('parse count (total)', 'execute count', 'user commits', 'user rollbacks')
`

**Comment by nqirod** [comment]
Without the heading :
 
user commits
       284
user rollbacks
	 0
parse count (total)
     18424
execute count
     81456

**Comment by cukal** [comment]
I got the same error when running it for the first time even without hitting /metrics, second & third restart went ok for a while, no error when scraping and after the fourth restart the error gets thrown right after startup or each time when calling /metrics. 

```
oracle@***** oracle_exporter]$ ./oracledb_exporter.linux-amd64 -log.format logger:stdout -log.level debug
INFO[0000] Starting oracledb_exporter 0.0.6              source=main.go:407
ERRO[0002] Error scraping for wait_time: sql: Scan error on column index 1: converting driver.Value type string (",001") to a float64: invalid syntax  source=main.go:154
INFO[0002] Listening on :9161                            source=main.go:415
```

From sqlplus: 
```
SQL> SELECT name, value FROM v$sysstat WHERE name IN ('parse count (total)', 'execute count', 'user commits', 'user rollbacks');

NAME								      VALUE
---------------------------------------------------------------- ----------
user commits							    5796250
user rollbacks							      10962
parse count (total)						  244890767
execute count							  924452065
```

Sometimes the error value changes: 
```
ERRO[0000] Error scraping for wait_time: sql: Scan error on column index 1: converting driver.Value type string (",005") to a float64: invalid syntax  source=main.go:154
```

Oracle 11.2.0 & instantclient-basic-linux.x64-12.1.0.2.0.zip

**Comment by gbloquel** [comment]
By updating the NS_LANG with a value where the NLS_NUMERIC_CHARACTERS is '.' and there is no problem.
I solved by adding an environment variable `NLS_LANG=AMERICAN_AMERICA.WE8ISO8859P15`
If you use docker container add  `-e NLS_LANG=AMERICAN_AMERICA.WE8ISO8859P15` in run command.

**Comment by iamseth** [comment]
Added a note to the README. Thanks for your help @cukal  and @gbloquel
