### ISSUE TITLE
release 0.3.2 docker images

### ISSUE THREAD

**Issue by fra2p0** [iamseth/oracledb_exporter#222]
Hello, 

I would like to use oracledb_exporter docker images (oracle linux preferably) in my project, but I noticed that docker hub is not updated with the 0.3.2 tag.
Is it possible to push it there ?

thanks

**Comment by Yannig** [comment]
The credentials used by this project are broken and we need to use a different one.

I have pushed the image at the following location: quay.io/yannig/oracledb_exporter. Can you try it and get me some feedback?

**Comment by fra2p0** [comment]
Hello, 
Thanks, but I cannot browse to this location, I can see 4 repositories for user yannig (postgres-operator, bats, keycloak-operator, dog), maybe it needs to be public ?

**Comment by Yannig** [comment]
Sorry, I have problem with my old account on quay.io. Can you try to use this image: quay.io/yannig0/oracledb_exporter:0.3.2

**Comment by pike1212** [comment]
How was this resolved? Does the quay.io url require an account to pull?
