### ISSUE TITLE
Why does oracledb_exporter generate audit log files when it is running? Where is the sys user used?

### ISSUE THREAD

**Issue by ymlzhiyang** [iamseth/oracledb_exporter#233]
When it is running, it will generate lots of audit files every acquisition interval (10 seconds), resulting in a large number of audit files. However, no users related to SYSDBA or SYS were found in the source code. 

I hope you can answer my question, thank you so much.

**Comment by Yannig** [comment]
In Oracle, when you connect locally with the / as sysdba or something similar, you get audit files generated for each connection.

I don't have much solution for this problem except removing them using a script launched by the crontab ...
