### ISSUE TITLE
Exporter process memory keeps increasing with time 

### ISSUE THREAD

**Issue by yashtessell** [iamseth/oracledb_exporter#235]
I am not here to report an issue but I have more of a question about the oracle exporter's behavior.
I am running the exporter in a pod/container and we are observing the exporter process memory keeps increasing with time (about 2MB every 5min).

I enabled pprof in the exporter and the profiler only indicates the exporter is taking 1-2MB of heap space. While top shows the process is taking ~45MB. Eventually, the pod reaches its allocated memory limits and restarts.

I noticed the memory suddenly jumps if a metric sweep from Prometheus comes in (request on /metrics endpoint).
I am trying to make sense of it all and figure out why this is happening.

Any help is appreciated. Thanks. 

For reference, I am including the output of pprof

Showing nodes accounting for **1447.25kB**, 100% of 1447.25kB total
      flat  flat%   sum%        cum   cum%
  902.59kB **62.37%** 62.37%  1447.25kB   100%  **compress/flate.NewWriter**
  544.67kB **37.63%**   100%   544.67kB 37.63%  **compress/flate.newDeflateFast (inline)**
         0     0%   100%   544.67kB 37.63%  compress/flate.(*compressor).init
         0     0%   100%  1447.25kB   100%  compress/gzip.(*Writer).Write
         0     0%   100%  1447.25kB   100%  net/http.(*ServeMux).ServeHTTP
         0     0%   100%  1447.25kB   100%  net/http.(*conn).serve
         0     0%   100%  1447.25kB   100%  net/http.HandlerFunc.ServeHTTP
         0     0%   100%  1447.25kB   100%  net/http.serverHandler.ServeHTTP

**Comment by mymasse** [comment]
We are seeing the same behavior where the memory usage increases with time.

**Comment by yashtessell** [comment]
@mymasse we were able to fix the problem. Turns out if a connection to the db fails for whatever reason, db conn objects hang around causing memory usage to increase over time.
we resolved the issue by passing a timeout parameter while configuring the db connect string in the exporter during exporter configuration.

**Comment by mymasse** [comment]
@yashtessell Where did you set a connection timeout and with was parameter?

**Comment by yashtessell** [comment]
From the examples in the README in this repo, you will find the following @mymasse :

export DATA_SOURCE_NAME=user/password@//primaryhost:1521,standbyhost:1521/service?connect_timeout=5

**Comment by adriantaut-pp** [comment]
hitting the same issue, no DB timeouts, yet the memory constantly increase until it consumes all the memory
