### ISSUE TITLE
There are two Oracle instances on the same host，DATA_SOURCE_NAME How to write？

### ISSUE THREAD

**Issue by vpnxiaodu001** [iamseth/oracledb_exporter#240]
There are two Oracle instances on the same host，DATA_SOURCE_NAME How to write？

export DATA_SOURCE_NAME=user/password@//ORADB:1521/ORCL1,ORADB:1521/ORCL2
Is this OK？

**Comment by Yannig** [comment]
Hello,

You have two different database so you have to start two different exporter.
