### ISSUE TITLE
Any post 0.3.2 release planned?

### ISSUE THREAD

**Issue by indicum** [iamseth/oracledb_exporter#252]
Hi,
I was trying to find if there was any 0.3.2 release planned but can't find info.
Is there anything planned?

**Comment by Yannig** [comment]
Hello,

Actually, there's already improvements on the current code. In fact, it have been tested on my side since a couple of week. So I guess, it's time for a release :)

Regards

**Comment by blalop** [comment]
Hi,

Just wanted to know, is there any planned release any time soon? Looking forward to use the new `scrape.interval` flag :sunglasses: 

Thank you so much for the good work!

**Comment by vutkin** [comment]
It was released: yannig/oracledb_exporter:0.3.2

**Comment by vutkin** [comment]
Please use next image: yannig/oracledb_exporter:0.3.2

**Comment by blalop** [comment]
Hi @vutkin, I don't think the flag was released yet... can't see it in the source code for 0.3.2 tag :(

**Comment by indicum** [comment]
I think you are right @blalop. 0.3.2 was released in Sept 2021 and the flag was introduced in March 2022:
https://github.com/iamseth/oracledb_exporter/commit/6c979a3f7f2c8027f8b4a375062993084ba116d8

**Comment by Yannig** [comment]
Hello there,

You can download the future version (0.4.0) with Docker. Here the link to retrieve it:
https://hub.docker.com/layers/yannig/oracledb_exporter/0.4.0/images/sha256-c29ba7afc61a0cf3c64a39371074d042013460ef82362ae8876a321869ed20da?context=repo

**Comment by indicum** [comment]
released: https://github.com/iamseth/oracledb_exporter/releases/tag/0.4.0
