### ISSUE TITLE
Not compatible with oracle19c

### ISSUE THREAD

**Issue by laoxiaokang** [iamseth/oracledb_exporter#253]
I hope to release a new version to get enough indicators

**Comment by mp2350** [comment]
We are having similar issue, not working with Oracle 19c client

**Comment by KoerberIng** [comment]
Same, No working with Oracle 19.3 :(

**Comment by laoxiaokang** [comment]
@KoerberIng  OK ,I know, Thanks!

**Comment by Yannig** [comment]
Did you try to build the source version?
You can also retrieve the last version from Docker:
https://hub.docker.com/layers/yannig/oracledb_exporter/0.4.0/images/sha256-c29ba7afc61a0cf3c64a39371074d042013460ef82362ae8876a321869ed20da?context=repo
