### ISSUE TITLE
Build linux binary from source in 0.4.0

### ISSUE THREAD

**Issue by guruguruguru** [iamseth/oracledb_exporter#275]
Hi,

linux was removed from the Makefile. How can I now build the exporter now?

Edit: I am trying the go-build but this results in:

./main.go:620:39: cannot use *tlsconfigFile (variable of type string) as type *web.FlagConfig in argument to web.ListenAndServe

Thanks,
Dennis

**Comment by vutkin** [comment]
Have you tried to run next command for build?
```bash
make go-build
```

**Comment by guruguruguru** [comment]
Hi @vutkin 
yes I did. With go-build I get the error above:

./main.go:620:39: cannot use *tlsconfigFile (variable of type string) as type *web.FlagConfig in argument to web.ListenAndServe

**Comment by vutkin** [comment]
Just check how we do it via github-action: https://github.com/iamseth/oracledb_exporter/actions/runs/4058703486/workflow#L94-L109

**Comment by vutkin** [comment]
> ```shell
> make oci.pc prereq
> ```

sorry, forgot to add
```bash
make oci.pc prereq
```

**Comment by guruguruguru** [comment]
I tried both, 0.4.0 and master. Also, I build for Oracle 10,11,12,19 and not 21 but this does not seem to be the issue.

golang version is 1.18.9

**Comment by vutkin** [comment]
Please try this commit: b4155d249e4caeb0480b946bad4c74a5d1a918f6, it works for me

**Comment by guruguruguru** [comment]
Yes, works, thank you.

**Comment by guruguruguru** [comment]
FYI: it also builds on CentOS7 now, Oracle 10, 11, 12

**Comment by guruguruguru** [comment]
Tank you very much for your support here!
