### ISSUE TITLE
Errorscrapingfor=XXXX _="unsupported value type" 5.005935854s=:

### ISSUE THREAD

**Issue by mjnman** [iamseth/oracledb_exporter#287]
I'm using a container with version 0.4.1 and custom queries. In random time obtain an error as below without metric data:

ts=2023-02-08T13:36:17.611Z caller=main.go:316 level=error Errorscrapingfor=sga _="unsupported value type" 5.005935854s=:

The metric syntax is:

[[metric]]
context = "sga"
labels = [ "database" ]
metricsdesc = { usages = "SGA Usage" }
request = '''
SELECT distinct(regexp_substr(t.target_name, '[^_]+', 1, 1)) database,
     SUBSTR(h.host_name, 1, 9) as host,
     m.value as usages
FROM sysman.MGMT$METRIC_CURRENT M,
     sysman.mgmt$target_type T,
     sysman.MGMT$DB_DBNINSTANCEINFO H
WHERE t.target_type in ('rac_database','oracle_database')
      and m.target_guid=t.target_guid
      and m.metric_guid=t.metric_guid
      and h.target_guid=t.target_guid
      and t.metric_name='memory_usage_sga_pga'
      and t.metric_column='sga_total'
'''

The query work correctly but sometimes obtain the error "unsupported value type" 5.005935854s=:.
Maybe a timeount in the query executions? I used the parameter timeout at 30 seconds in connection with: 

DATA_SOURCE_NAME=grafana/XXXXX@hostname:1521/ALIAS_TNS?connect_timeout=30&transport_connect_timeout=30&retry_count=3

The same issue and holes in the data with other metrics and different query. Seems to be a timeout in about 5 seconds of query execution. The Oracle Database, prometheus and oracledb_exporter is in the same host.
The prometheus scheduler execute the requests every 5 minutes.

![sga_prometheus](https://user-images.githubusercontent.com/8179167/217549950-4b4cef36-d10d-4253-bbc9-38d8e02dae58.png)

**Comment by mjnman** [comment]
I set the value in the environment variable QUERY_TIMEOUT upper to 5 seconds and now all queries work correctly without errors in container logs and holes in prometheus graphs.
I'm sorry, I didn't check the main.go file code.

**Comment by spanishkangaroo** [comment]
@mjnman could you please document how can anyone set that QUERY_TIMEOUT in order to help others?

**Comment by mjnman** [comment]
You can set in binary execution with classic OS export "export QUERY_TIMEOUT=30" or by container run variable with:

docker run -d --name oracledb_exporter_edited_0_4_2 -p 9161:9161 -e "DATA_SOURCE_NAME=USER/PWD@HOST_DB:1521/SERVICE_NAME"  -e LD_LIBRARY_PATH=/usr/lib/oracle/21/client64/lib -e QUERY_TIMEOUT=30 -v /etc/oracledb_exporter:/metrics oracledb_exporter_edited_0_4_2

ENTRYPOINT ARGS: ["/oracledb_exporter","--default.metrics","/metrics/default-metrics.toml","--custom.metrics","/metrics/container-metrics.toml"]
