### ISSUE TITLE
run exporter on apline

### ISSUE THREAD

**Issue by andridzi** [iamseth/oracledb_exporter#29]
hi
could you please advise how to run it on alpine?

**Comment by Yannig** [comment]
Actually, the exporter is written in go but depend on oracle libs. I don't know if it's possible to install this libs on alpine.
Why don't you try to run this exporter in Docker?

**Comment by andridzi** [comment]
I want to build docker image build on alpine image

**Comment by Yannig** [comment]
OK. I will take a look.

**Comment by andridzi** [comment]
thanks a lot

**Comment by Yannig** [comment]
Just a quick feedback: actually, alpine cannot run instant client (libresolv is broken). I'll take a look at this package if it can fix this issue:
https://github.com/sgerrand/alpine-pkg-glibc

**Comment by Yannig** [comment]
The docker repository have now a 0.2.1 release with Alpine flavor (use alpine or 0.2.1-alpine tag).
Can you try them and give me a feedback?

**Comment by andridzi** [comment]
yes, sure
will try it today
thanks

**Comment by andridzi** [comment]
it works!
thank you very much!

**Comment by Yannig** [comment]
Fine :)
