### ISSUE TITLE
Dependencies versions not alligned in the same release

### ISSUE THREAD

**Issue by IAmCaramelo** [iamseth/oracledb_exporter#297]
## I'm submitting a ...

- [x ] bug report
- [ ] feature request

## What is the current behavior?
The exporter delivered in the tar.gz does not match some golang package versions

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
There is a difference regarding dependencies versions in the same release 0.4.3 where the binary (oracledb_exporter.tar.gz) and the Source code (zip) 

**From zip file (go.mod)**
github.com/prometheus/common **v0.39.0** h1:oOyhkDq05hPZKItWVBkJ6g6AtGxi+fy7F4JvUV8uhsI=
github.com/prometheus/common **v0.39.0**/go.mod h1:6XBZ7lYdLCbkAVhwRsWTZn+IN5AB9F/NXd5w0BbEX0Y=
golang.org/x/net **v0.0.0-20190603091049-60506f45cf65**/go.mod h1:HSz+uSET+XFnRR8LxR5pz3Of3rY3CfYBVs4xY44aLks=
golang.org/x/net **v0.4.0** h1:Q5QPcMlvfxFTAPV0+07Xz/MpK9NTXu2VDUuy0FeMfaU=
golang.org/x/net **v0.4.0**/go.mod h1:MBQ8lrhLObU/6UmLb4fmbmk5OcyYmqtbGd/9yIeKjEE=
golang.org/x/sys **v0.0.0-20190215142949-d0b11bdaac8a**/go.mod h1:STP8DvDyc/dI5b8T5hshtkjS+E42TnysNCUPdjciGhY=
golang.org/x/sys **v0.3.0** h1:w8ZOecv6NaNa/zC8944JTU3vz4u6Lagfk4RPQxv92NQ=
golang.org/x/sys **v0.3.0**/go.mod h1:oPkhp1MJrh7nUepCBck5+mAzfO9JrbApNNgaTdGDITg=
golang.org/x/text **v0.3.0/**go.mod h1:NqM8EUOU14njkJ3fqMW+pc6Ldnwhi/IjpwHt7yyuwOQ=
golang.org/x/text **v0.3.2**/go.mod h1:bEr9sfX3Q8Zfm5fL9x+3itogRgK3+ptLWKqgva+5dAk=
golang.org/x/text **v0.5.0** h1:OLmvp0KP+FVG99Ct/qFiL/Fhk4zp4QQnZ7b2U+5piUM=
golang.org/x/text **v0.5.0**/go.mod h1:mrYo+phRRbMaCq/xk9113O4dZlRixOauAjOtrjsXDZ8=

**From binary packages** 
github.com/prometheus/common                      **v0.40.0**                             go-module 
golang.org/x/net                                  **v0.7.0**                              go-module 
golang.org/x/sys                                  **v0.5.0**                              go-module 
golang.org/x/text                                 **v0.7.0**                              go-module 

## What is the expected behavior?
All dependencies version should match all release forms (binary from the tar.gz and zips)

## What is the motivation / use case for changing the behavior?
Alligned versions throughout all release forms and avoid vulnerability triggers in the same release

## Please tell us about your environment:
Linux fedora 37

Version: 0.4.3

**Comment by Yannig** [comment]
Last release of the exporter should have fixed this issue. Can you check that it's ok?
