### ISSUE TITLE
 Unable to convert current value to float

### ISSUE THREAD

**Issue by user-with-name** [iamseth/oracledb_exporter#299]
## I'm submitting a error

custom-metric.toml 

[[metric]]
context = "slow_queries"
labels = [ "tablespace" ]
request = "select tablespace_name as tablespace, used_percent from DBA_TABLESPACE_USAGE_METRICS"
metricsdesc = { tablespace = "name of tablespace", used_percent = "used space percent value" }

ERRO[3095] Unable to convert current value to float (metric=tablespace_name,metricHelp=name of tablespace,value=<>xxxxx)  source="main.go:318"
DEBU[3095] Query result looks like:  xxxxxxxx  source="main.go:322"
ERRO[3095] Unable to convert current value to float (metric=tablespace_name,metricHelp=name of tablespace,value=<>xxxxx)  source="main.go:318"
DEBU[3095] Query result looks like:  xxxxxxxx    source="main.go:322"
DEBU[3095] Query result looks like:  xxxxxxxx     source="main.go:322"
ERRO[3095] Unable to convert current value to float (metric=tablespace_name,metricHelp=name of tablespace,value=<>xxxxx)  source="main.go:318"
ERRO[3095] Unable to convert current value to float (metric=tablespace_name,metricHelp=name of tablespace,value=<>xxxxx)  source="main.go:318"
DEBU[3095] Query result looks like:  xxxxxxxx     source="main.go:322"
ERRO[3095] Unable to convert current value to float (metric=tablespace_name,metricHelp=name of tablespace,value=<>xxxxx)  source="main.go:318"
DEBU[3095] Query result looks like:  xxxxxxxx    source="main.go:322"
ERRO[3095] Unable to convert current value to float (metric=tablespace_name,metricHelp=name of tablespace,value=<>xxxxx)  source="main.go:318"
DEBU[3095] Query result looks like:  xxxxxxxx    source="main.go:322"

**Comment by X-OppenHeimer-X** [comment]
Hi @user-with-name:

I am facing a similar issue here #357. Can you please explain how you resolved this issue?

**Comment by shaxiaozz** [comment]
You can take a look at the answer to this question https://github.com/iamseth/oracledb_exporter/issues/310, I hope it helps you
