### ISSUE TITLE
can you pls make a 64bit cenos release?

### ISSUE THREAD

**Issue by empo007** [iamseth/oracledb_exporter#3]
can you pls make a 64bit cenos release?

thanks

**Comment by Keleir** [comment]
The same needs for centos 64bit.

**Comment by iamseth** [comment]
Pretty late to this but here's a 64bit linux build
https://github.com/iamseth/oracledb_exporter/releases/download/0.0.1/oracledb_exporter-0.0.1.linux.x86_64
