### ISSUE TITLE
Add Customization metrics Abnormal exit

### ISSUE THREAD

**Issue by alazytomcat** [iamseth/oracledb_exporter#309]
Version: 0.2.3

Added several custom SQL statements

In actual testing, it was found that after the collector started normally, it exited abnormally after about 30 minutes. The detailed error message is as follows

![image](https://user-images.githubusercontent.com/117699548/232710080-78626052-aab0-4ae1-ac10-a61ea2f90a65.png)

**Comment by Yannig** [comment]
Hi,

You are using a very old version of the exporter. Maybe you can try a newer one?

Regards
