### ISSUE TITLE
New to Oracle, so forgive the daft questions

### ISSUE THREAD

**Issue by johndnlightnit** [iamseth/oracledb_exporter#319]
Running the latest release as a binary, and running the exporter on oracle Linux 8.5 I get the following error: Caller=collector.90.260 level=error ErrorPingingoracle:-missing port in address. 

I am trying to connect to Oracle 19 DB. 

I have set the DATA Source

with both 

export DATA_SOURCE_NAME=system/password@oracle-sid
export DATA_SOURCE_NAME=user/password@//myhost:1521/service
then
./oracle_exporter

Types but when I run the program, it runs but is not able to connect to the DB. With the ErrorPingingoracle:-missing port in address. 

What am I doing wrong?

And to confirm 
export DATA_SOURCE_NAME=user/password@//myhost:1521/service
service is the service name of the Database?

regards and thanx in advance
J.

![runningerror](https://user-images.githubusercontent.com/46019940/236354600-445ae0ab-50c6-413e-a4a6-b1b9a6b05a36.jpg)

**Comment by ziyanTOP** [comment]
This exporter is using new oracle driver in latest master branch, so maybe the document is outdated. The new data source name should look like the one below

```shell
export DATA_SOURCE_NAME=oracle://user:pass@server/service_name
```

according to [sijms/go-ora](https://github.com/sijms/go-ora#2--create-the-connection) repository

**Comment by johndnlightnit** [comment]
Changed as suggested, and slightly new error. (Thanks for advic
![runningerror](https://user-images.githubusercontent.com/46019940/236389161-91c5b172-b680-43a6-b3e5-49cc086c4fc6.jpg)
e)

**Comment by johndnlightnit** [comment]
Is this:


url := go_ora.BuildUrl("server", 1521, "service", "user", "pass", nil)

println(url)

Dealt with in you version of the exporter, as I was just running the one as downloaded. Or are you suggesting I may have special chars in my password.

Cheers

John

**Comment by johndnlightnit** [comment]
Worked it out cheers, ran it through a small go program and got the special password with the escaped details, so Ill test.

Cheers

J.

**Comment by johndnlightnit** [comment]
Worked like a charm cheers.
