### ISSUE TITLE
Not working after DB restart

### ISSUE THREAD

**Issue by Bayardalai** [iamseth/oracledb_exporter#32]
Hi,

The exporter is not collecting metrics after DB restart. It's not creating new connection to database.
"Error pinging oracle: ORA-03114: not connected to ORACLE\n" source="main.go:168"

Thanks,

**Comment by Yannig** [comment]
What version of the exporter that you use?

**Comment by Bayardalai** [comment]
I'm using latest docker image.

**Comment by Bayardalai** [comment]
I tried linux binary release 0.2.1. But same result
  source=main.go:168
ERRO[0619] Error pinging oracle: ORA-03114: not connected to ORACLE
  source=main.go:168
ERRO[0620] Error pinging oracle: ORA-03114: not connected to ORACLE

**Comment by Yannig** [comment]
The release 0.2.2 (and latest) have a fix for your issue. Can you give it a try ?
Regards

**Comment by Bayardalai** [comment]
I've test it and work fine. Thanks
