### ISSUE TITLE
README.md not updated regarding latest changes in 0.5.0

### ISSUE THREAD

**Issue by mymasse** [iamseth/oracledb_exporter#320]
## I'm submitting a ...

- [X] bug report
- [ ] feature request

## What is the current behavior?

README.md file has not been updated to reflect changes in the 0.5.0.
- Datasource URL format has been changed
- Default Metrics TOML file is not overidable anymore

Version: 0.5.0

**Comment by schmikei** [comment]
I've created #324 to re-add the feature. Was an oversight when I did the refactor. Sorry for the inconvenience.
