### ISSUE TITLE
"panic: assignment to entry in nil map" when using custom metrics as of 0.5.0

### ISSUE THREAD

**Issue by 9numbernine9** [iamseth/oracledb_exporter#321]
## I'm submitting a ...

- [X] bug report
- [ ] feature request

## What is the current behavior?

When using custom metrics, a Go stack trace is generated:
```
github.com/iamseth/oracledb_exporter/collector.(*Exporter).checkIfMetricsChanged(0xc000290000)
    /go/src/oracledb_exporter/collector/collector.go:353 +0x3e5
<snip>
panic: assignment to entry in nil map
```

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem

Specfying a `CUSTOM_METRICS` environment variable that points to a file with any custom metrics inside of it will do the trick.

## What is the expected behavior?

Custom metrics behave as they did previously in `0.4.4`.

## What is the motivation / use case for changing the behavior?

Using custom metrics. :smile: 

## Please tell us about your environment:

Version: 0.5.0

## NOTES

This appears to be a result of commit d0fbef97ca9e242477019fec3dc81e3f13d83b9d . Previously the `hashMap` was [being initialized in main.go](https://github.com/iamseth/oracledb_exporter/blob/ed103f54d78fe36a26febf3d24dab72842ef6257/main.go#L591) but since the refactoring this initialization step isn't being performed anywhere in `collector.go`, resulting in an attempt to index into an unitialized map.

**Comment by schmikei** [comment]
Thanks for finding this! Looking into this, I'm sorry for the inconvenience.

**Comment by gabguy** [comment]
@schmikei Can you please make a new release with this fix. Cannot use `docker pull` to get a valid container for version 0.5.0 with your fix atm.

**Comment by 9numbernine9** [comment]
@schmikei Sorry for not reporting back sooner but I can confirm that the latest release fixes the issue that I originally reported. Thank you for looking into it! 👍
