### ISSUE TITLE
Support common user

### ISSUE THREAD

**Issue by ostertagconrad** [iamseth/oracledb_exporter#332]
## I'm submitting a ...

- [ ] bug report
- [x] feature request

## What is the current behavior?

```
user@host ~ $ DATA_SOURCE_NAME='oracle://c##exporter:password@localhost:1521/SID' /usr/bin/oracle_exporter --default.metrics "/etc/oracle_exporter/default-metrics.toml" --web.listen-address host.domain.de:9161
ts=2023-06-02T09:36:15.956Z caller=collector.go:262 level=error Errorpingingoracle:="address c: missing port in address"
```

## What is the expected behavior?

Exporter does interpret the `#` correctly.

## What is the motivation / use case for changing the behavior?

The exporter in our environment connects to the CDB. In a CDB you can only create common users with the prefix `c##`. We could _somehow_ change this prefix in the instance but we don't really want to.

## Please tell us about your environment:

OS: Oracle Linux 8
Database: Oracle RDBMS 19.19
Exporter Version: 0.5.1

There is an issue at the used Oracle Library that also describes this problem: https://github.com/sijms/go-ora/issues/289
I can imagine this isn't trivial to implement in this project.

**Comment by OskarsPakers** [comment]
Does url escaping like this `DATA_SOURCE_NAME='oracle://c%23%23exporter:password@localhost:1521/SID'` fix the issue?

**Comment by ostertagconrad** [comment]
I thought I tested this and it didn't work. But now it works :tada: 

For use in a system unit file you need to escape the `%` with another `%`: `Environment="DATA_SOURCE_NAME=oracle://c%%23%%23exporter:password@localhost:1521/SID"`

Thank you very much.
