### ISSUE TITLE
 level=error Errorscrapingfor=wait_time 

### ISSUE THREAD

**Issue by xiajing869** [iamseth/oracledb_exporter#343]
ts=2023-06-20T09:46:10.460Z caller=main.go:71 level=info msg="Build context" build="(go=go1.19.4, platform=linux/amd64, user=, date=, tags=u
nknown)"
ts=2023-06-20T09:46:10.460Z caller=main.go:72 level=info msg="Collect from: " metricPath=/metrics
ts=2023-06-20T09:46:10.460Z caller=tls_config.go:274 level=info msg="Listening on" address=[::]:9161
ts=2023-06-20T09:46:10.460Z caller=tls_config.go:277 level=info msg="TLS is disabled." http2=false address=[::]:9161
ts=2023-06-25T02:05:07.507Z caller=collector.go:315 level=error Errorscrapingfor=resource _="unsupported value type" 70.412986ms=:
ts=2023-06-25T02:05:07.513Z caller=collector.go:315 level=error Errorscrapingfor=wait_time _="unsupported value type" 77.00947ms=:
ts=2023-06-25T02:05:12.444Z caller=collector.go:315 level=error Errorscrapingfor=tablespace _="unsupported value type" 5.007796994s=:
ts=2023-06-25T02:05:17.134Z caller=collector.go:315 level=error Errorscrapingfor=resource _="unsupported value type" 48.293984ms=:
ts=2023-06-25T02:05:17.139Z caller=collector.go:315 level=error Errorscrapingfor=wait_time _="unsupported value type" 52.641293ms=:
ts=2023-06-25T02:05:22.091Z caller=collector.go:315 level=error Errorscrapingfor=tablespace _="unsupported value type" 5.005214492s=:

**Comment by OskarsPakers** [comment]
Does db user have sufficient access rights?
https://github.com/iamseth/oracledb_exporter#default-metrics-requirement
