### ISSUE TITLE
missing port in address

### ISSUE THREAD

**Issue by Neurozone** [iamseth/oracledb_exporter#345]
I have an issue with the exporter
got this error:

Errorpingingoracle:="missing port in address"

but the service is setup as 

root@pageplace31: [/opt] 06:53:03# cat /etc/systemd/system/oracle_exporter.service
[Unit]
Description = Systemd unit for Prometheus Oracle Exporter
After = network.target

[Service]
Type = simple
User=oracle
Group=dba
Environment="DATA_SOURCE_NAME=oracle_exporter/*redacted*@//*ip redacted*:1521/*service redacted*"
Environment="ORACLE_HOME=***"
Environment="LD_LIBRARY_PATH=**"
ExecStart = /opt/oracledb_exporter-0.5.1.linux-amd64/oracledb_exporter
Restart = on-failure
RestartSec = 30s

[Install]
WantedBy = multi-user.target

So I don't understand

**Comment by Neurozone** [comment]
Version is 11.2.0.4

**Comment by erroltuparker** [comment]
I don't know what changed, but i noticed that I had to update my connections with oracle:// now

So based on your DATA_SOURCE_NAME it should now be
DATA_SOURCE_NAME=oracle://oracle_exporter/redacted@//ip redacted:1521/service redacted

**Comment by Neurozone** [comment]
Even with that it doesn't work

**Comment by saurabh-m-w** [comment]
I am still having this error with 0.5.2 version and with same above data source name, added detailed comment here https://github.com/iamseth/oracledb_exporter/issues/363#issuecomment-1934068278
