### ISSUE TITLE
unknown driver "oci8" error

### ISSUE THREAD

**Issue by jdv13** [iamseth/oracledb_exporter#36]
Hello,

When running release 0.22 (oracledb_exporter.0.2.2.darwin-amd64) I get the following when trying to execute:

/oracledb_exporter -log.level error -web.listen-address 9161
ERRO[0000] Error while connecting to user/password@MY_CONN  source=main.go:76
panic: sql: unknown driver "oci8" (forgotten import?)

goroutine 1 [running]:
main.NewExporter(0xc000018041, 0x1b, 0x0)
	/home/travis/gopath/src/github.com/iamseth/oracledb_exporter/main.go:77 +0x509
main.main()
	/home/travis/gopath/src/github.com/iamseth/oracledb_exporter/main.go:351 +0x1d1

I do have the DATA_SOURCE_NAME environment variable set and have verified connectivity to the DB using oracle client.  Thank you for your time and consideration!

**Comment by Yannig** [comment]
Can you try to upgrade your Oracle client to last version (18.3)?

**Comment by jdv13** [comment]
A college of mine tried with the latest, same result.  We were able to un using the docker image.  Is there a way to pass custom metrics configuration to the container?

**Comment by Yannig** [comment]
Of course, you can extend the docker image with a Dockerfile. I will add an example in the README.md file.

**Comment by Yannig** [comment]
Here's an example:
https://github.com/iamseth/oracledb_exporter#customize-metrics-in-a-docker-image

**Comment by jdv13** [comment]
We went with the docker image, which is working well so far.  Thanks!
