### ISSUE TITLE
Versions 0.2.1 and above don't work with Oracle client 12.2

### ISSUE THREAD

**Issue by wbh1** [iamseth/oracledb_exporter#37]
This is probably tangentially related to #34, but I want to continue discussion here.

TL;DR -- the Linux releases of versions 0.2.2 and 0.2.1 do not work with Oracle Client 12.2. I'm guessing this is due to cf9761dd2be6b72f4c5b252ed185d61df020098e or ab9debdddde06af6a0261e06177a3b455bad574d, but I wanted to confirm that this is expected behavior.

Is there some way to compile the binary in a way that allows for different versions of Oracle client to be installed on the target system?

**Comment by Yannig** [comment]
Sorry for the problem. I was anaware of this issue. I'll see if I rollback the dependencies back to 12.2

**Comment by Yannig** [comment]
The problem with oracle  you can't produce static binaries. Here, the exporter use last version of oracle lib (18.3).
If you need the last features of the exporter compiled with old oracle lib (12.2), you can still use version 0.1.1 from my repositories here: https://github.com/Yannig/oracledb_exporter/releases
