### ISSUE TITLE
prometheus metric naming best practices not followed

### ISSUE THREAD

**Issue by perkons** [iamseth/oracledb_exporter#372]
## I'm submitting a ...

- [ ] bug report
- [x] feature request

## What is the current behavior?
The metric name "oracledb_tablespace_free" does not follow the Prometheus naming best practices documented here: https://prometheus.io/docs/practices/naming/

A change would need to be done in the following lines:
https://github.com/iamseth/oracledb_exporter/blob/master/default-metrics.toml#L48
https://github.com/iamseth/oracledb_exporter/blob/master/default-metrics.toml#L55
I am not sure about this line https://github.com/iamseth/oracledb_exporter/blob/master/default-metrics.toml#L17 but it looks like this one too should be "free_bytes"

## What is the expected behavior?
Expected metric name would be "oracledb_tablespace_free_bytes"

**Comment by Yannig** [comment]
Hi,

The name is quite old. If we change it, it will broke existing dashboards.

But you can do a PR if you want to change it.
