### ISSUE TITLE
Update to latest version of golang.org/x/net due to security vulnerability

### ISSUE THREAD

**Issue by gjrlopes** [iamseth/oracledb_exporter#378]
Is it possible to include this update in next version?
https://github.com/advisories/GHSA-4374-p667-p6c8

If possible, update all dependencies.
When it's expected the delivered of new oracledb_exporter version?

Version: 0.5.1

**Comment by Yannig** [comment]
Last master version is now ok. Could you check?

**Comment by gjrlopes** [comment]
Hi @Yannig 

I ran trivy with 0.5.2 binary and it seems ok.
Total: 0 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 0)

Thank you
