### ISSUE TITLE
Error scraping for tablespace : Oracle query timed out

### ISSUE THREAD

**Issue by duhongx** [iamseth/oracledb_exporter#39]
[root@ecs-01 oracledb_exporter.0.2.1.linux-amd64]# ./oracledb_exporter -log.level debug -web.listen-address :9161 -default.metrics default-metrics.toml 
INFO[0000] Starting oracledb_exporter 0.2.1              source=main.go:323
ERRO[0012] Error scraping for tablespace : Oracle query timed out  source=main.go:176
INFO[0012] Listening on :9161                            source=main.go:345
ERRO[0029] Error scraping for tablespace : Oracle query timed out  source=main.go:176
ERRO[0045] Error scraping for tablespace : Oracle query timed out  source=main.go:176
ERRO[0058] Error scraping for tablespace : Oracle query timed out  source=main.go:176

What is the reason for this mistake?

**Comment by Yannig** [comment]
You have a problem in your Oracle instance. You need to figure out why this request is to long to send your result back:

```sql
  SELECT
    Z.name       as tablespace,
    dt.contents  as type,
    Z.bytes      as bytes,
    Z.max_bytes  as max_bytes,
    Z.free_bytes as free
  FROM
  (
    SELECT
      X.name                   as name,
      SUM(nvl(X.free_bytes,0)) as free_bytes,
      SUM(X.bytes)             as bytes,
      SUM(X.max_bytes)         as max_bytes
    FROM
      (
        SELECT
          ddf.tablespace_name as name,
          ddf.status as status,
          ddf.bytes as bytes,
          sum(coalesce(dfs.bytes, 0)) as free_bytes,
          CASE
            WHEN ddf.maxbytes = 0 THEN ddf.bytes
            ELSE ddf.maxbytes
          END as max_bytes
        FROM
          sys.dba_data_files ddf,
          sys.dba_tablespaces dt,
          sys.dba_free_space dfs
        WHERE ddf.tablespace_name = dt.tablespace_name
        AND ddf.file_id = dfs.file_id(+)
        GROUP BY
          ddf.tablespace_name,
          ddf.file_name,
          ddf.status,
          ddf.bytes,
          ddf.maxbytes
      ) X
    GROUP BY X.name
    UNION ALL
    SELECT
      Y.name                   as name,
      MAX(nvl(Y.free_bytes,0)) as free_bytes,
      SUM(Y.bytes)             as bytes,
      SUM(Y.max_bytes)         as max_bytes
    FROM
      (
        SELECT
          dtf.tablespace_name as name,
          dtf.status as status,
          dtf.bytes as bytes,
          (
            SELECT
              ((f.total_blocks - s.tot_used_blocks)*vp.value)
            FROM
              (SELECT tablespace_name, sum(used_blocks) tot_used_blocks FROM gv$sort_segment WHERE  tablespace_name!='DUMMY' GROUP BY tablespace_name) s,
              (SELECT tablespace_name, sum(blocks) total_blocks FROM dba_temp_files where tablespace_name !='DUMMY' GROUP BY tablespace_name) f,
              (SELECT value FROM v$parameter WHERE name = 'db_block_size') vp
            WHERE f.tablespace_name=s.tablespace_name AND f.tablespace_name = dtf.tablespace_name
          ) as free_bytes,by launching 
          CASE
            WHEN dtf.maxbytes = 0 THEN dtf.bytes
            ELSE dtf.maxbytes
          END as max_bytes
        FROM
          sys.dba_temp_files dtf
      ) Y
    GROUP BY Y.name
  ) Z, sys.dba_tablespaces dt
  WHERE
    Z.name = dt.tablespace_name
```

Unfortunately my skills on oracle stop there.

**Comment by duhongx** [comment]
thanks，i delete the SQL from default-metrics.toml and execute the script as normal
[root@ecs-01 oracledb_exporter.0.2.1.linux-amd64]# ./oracledb_exporter -log.level debug -web.listen-address :9161 -default.metrics default-metrics.toml
INFO[0000] Starting oracledb_exporter 0.2.1              source=main.go:323
INFO[0000] Listening on :9161                            source=main.go:345

**Comment by Mayezi** [comment]
Hi, I am having this problem too. It took close to 50 seconds to execute the default configured tablespace query SQL, so I was wondering if there was a way to increase the query time to solve this problem, since I really need this tablespace monitoring.

**Comment by Yannig** [comment]
Hi,

You can use QUERY_TIMEOUT to set a higher value (or -query.timeout option) using the last version of this exporter. You also need to set a higher value on Prometheus.

As a side note, I think that a scrape must stay below 5 seconds. The upper limit - from my point of view - is never to exceed 15 seconds. In the past, I have already had poor response times for this specific request. In this case, it may be better to write a simpler tablespace query that will launch instantly or even find the source of the problem with your Oracle administrator.

**Comment by Mayezi** [comment]
> Hi,
> 
> You can use QUERY_TIMEOUT to set a higher value (or -query.timeout option) using the last version of this exporter. You also need to set a higher value on Prometheus.
> 
> As a side note, I think that a scrape must stay below 5 seconds. The upper limit - from my point of view - is never to exceed 15 seconds. In the past, I have already had poor response times for this specific request. In this case, it may be better to write a simpler tablespace query that will launch instantly or even find the source of the problem with your Oracle administrator.

Thanks, I set QUERY_TIMEOUT to 1m and changed the prometheus related configuration,it worked.Next I will contact DBA to deal with this problem, thanks again!

**Comment by abhishek-verma-maersk** [comment]
I have added -- QUERY_TIMEOUT 40 sec and it's works for me.
