### ISSUE TITLE
Cannot display metrics that added in the my-custom-metrics.toml on Grafana

### ISSUE THREAD

**Issue by LizZzxx** [iamseth/oracledb_exporter#41]
Hi,
Thanks a lot for your exporter, it helps a lot for my job!
Here is question that I encountered during using this exporter, that is:

1、I have added a metric via my-custom-metrics.toml_

[[metric]]
context = "libraryCache"
labels = ["namespace"]
metricsdesc = { pinhits= "objects in cache", pins="all of the objects that executed", reloads="Total reload counts", invalidations="Metric with objects miss counts"}
request = "SELECT namespace, pinhits, pins, reloads, invalidations FROM v$librarycache"
metricstype = {  namespace= "gauge" }

2、I can also get the metrics via Prometheus http://XXXXX:9090

oracledb_libraryCache_pins{instance="oracle",job="rac_oracle",namespace="ACCOUNT_STATUS"} | 0
-- | --
oracledb_libraryCache_pins{instance="oracle",job="rac_oracle",namespace="BODY"} | 110107
oracledb_libraryCache_pins{instance="oracle",job="rac_oracle",namespace="CLUSTER"} | 1800
oracledb_libraryCache_pins{instance="oracle",job="rac_oracle",namespace="DBINSTANCE"} | 0
oracledb_libraryCache_pins{instance="oracle",job="rac_oracle",namespace="DBLINK"} | 0
oracledb_libraryCache_pins{instance="oracle",job="rac_oracle",namespace="DIRECTORY"} | 16
oracledb_libraryCache_pins{instance="oracle",job="rac_oracle",namespace="EDITION"} | 2294
oracledb_libraryCache_pins{instance="oracle",job="rac_oracle",namespace="INDEX"} | 5548
oracledb_libraryCache_pins{instance="oracle",job="rac_oracle",namespace="OBJECT ID"} | 0
oracledb_libraryCache_pins{instance="oracle",job="rac_oracle",namespace="QUEUE"}

3、The question is I cannot get the value of metrics via Grafana??

Regarding for your answers!
Thanks a lot!

**Comment by Yannig** [comment]
Hi,

You need to edit your Grafana dashboard in order to get your metrics.

Are you able to view your metrics in field to query Prometheus?

Regards,

Yannig

**Comment by Seth1u** [comment]
Hi,

I have installed binary sources on my Oracle Linux server running with Oracle 12 c. 

Can you show me right oracledb_exporter.service example that work and how to make my own collector for metrics please?

Thanks

**Comment by pnrmx** [comment]
> Can you show me right oracledb_exporter.service example that work 

```
cat > /etc/systemd/system/oracledb_exporter.service 
[Unit]
Description=Service for oracle telemetry client
After=network.target
[Service]
Type=oneshot
#User=oracledb_exporter
ExecStart=oracledb_exporter -log.level error -web.listen-address 0.0.0.0:9161
[Install]
WantedBy=multi-user.target
^D
```shell
where "^D" is keyboard ctrl-D.

Then check, that service works:

```shell
# systemctl daemon-reload
# systemctl start oracledb_exporter.service
# systemctl status oracledb_exporter.service
```

**Comment by Yannig** [comment]
README updated with this instructions.
