### ISSUE TITLE
How to connect multiple Data source

### ISSUE THREAD

**Issue by renuraj18** [iamseth/oracledb_exporter#43]
Please suggest how to connect multiple data source and get the guery output using this

**Comment by Yannig** [comment]
There is no way to connect multiple database at a time for a single exporter.

If you want to monitor multiple database on the same machine, you need to launch several time the exporter using different port (using -web.listen-address).

Regards

**Comment by renuraj18** [comment]
Thanks Yannig. I did the same but worndering if the datasource can be maintained inside the toml file for each DB

Regards
Renuraj

**Comment by Yannig** [comment]
That's a good idea. I will look if it is feasible. I will keep you informed

**Comment by athullya20** [comment]
Hi 
Please suggest how to connect multiple data source and get the guery output using this
