### ISSUE TITLE
Release 0.6.0  not satrt

### ISSUE THREAD

**Issue by anch665** [iamseth/oracledb_exporter#433]
Release 0.6.0  not satrt
```
 /usr/local/bin/oracledb_exporter --default.metrics /etc/oracledb_exporter/default-metrics.toml --log.level info --web.listen-address :9077 --query.timeout=120 --scrape.interval=60s
/usr/local/bin/oracledb_exporter: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by /usr/local/bin/oracledb_exporter)
/usr/local/bin/oracledb_exporter: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by /usr/local/bin/oracledb_exporter)
```
```
ll /lib64/libc.so.6
lrwxrwxrwx 1 root root 12 May 15  2018 /lib64/libc.so.6 -> libc-2.17.so
```

```
uname -a
Linux db01.domain.ru 4.1.12-124.14.5.el7uek.x86_64 #2 SMP Fri May 4 15:26:53 PDT 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by Yannig** [comment]
I think that your Linux version is to old. Can you try to upgrade to a newer version?

**Comment by anch665** [comment]
@Yannig I know that it is old, there is also no way to update or install docker

**Comment by Yannig** [comment]
I'm sorry to have to say this but I must remind you that this project is an open source project that works with an extremely expensive proprietary product.

If you really need to have recent versions of the exporter running on old OS versions, you can always contact me at my email.  I will be happy to provide you support to work on your needs through my regular job.

Regards

**Comment by xiaohaozifeifeifei** [comment]
I have a same question.

**Comment by xiaohaozifeifeifei** [comment]
> I think that your Linux version is to old. Can you try to upgrade to a newer version?

If I recompile with an earlier version of glibc, will it work fine on an older version of linux?

**Comment by DanielGUO123** [comment]
I have a same question.OS version：centos7.9 and Centos8.0
