### ISSUE TITLE
Race condition

### ISSUE THREAD

**Issue by valrusu** [iamseth/oracledb_exporter#459]
https://github.com/iamseth/oracledb_exporter/blame/29c8869cf60dc5b318236000f09fb69e92846620/collector/collector.go#L316

There is a race condition here, all the goroutines started using function f reference directly the err variable. When more than one change it at the same or close times, you get:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x9f2229]

goroutine 176881 [running]:
github.com/iamseth/oracledb_exporter/collector.(*Exporter).scrape.func2()
        .../oracledb_exporter/collector/collector.go:316 +0x13e9
created by github.com/iamseth/oracledb_exporter/collector.(*Exporter).scrape in goroutine 176838
        .../oracledb_exporter/collector/collector.go:322 +0x776

**Comment by levp7** [comment]
I'm seeing this issue :

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x9f7509]

goroutine 68477 [running]:
github.com/iamseth/oracledb_exporter/collector.(*Exporter).scrape.func2()
        /usr/local/gowork/src/github.com/oracledb_exporter/collector/collector.go:317 +0x1429
created by github.com/iamseth/oracledb_exporter/collector.(*Exporter).scrape in goroutine 68349
        /usr/local/gowork/src/github.com/oracledb_exporter/collector/collector.go:323 +0x796

**Comment by levp7** [comment]
I tested the previous release 0.5.2 and I'm also see similar issue :

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x9a825c]

goroutine 58783 [running]:
github.com/iamseth/oracledb_exporter/collector.(*Exporter).scrape.func2()
        /home/runner/work/oracledb_exporter/oracledb_exporter/collector/collector.go:315 +0xffc
created by github.com/iamseth/oracledb_exporter/collector.(*Exporter).scrape
        /home/runner/work/oracledb_exporter/oracledb_exporter/collector/collector.go:321 +0x94e

**Comment by valrusu** [comment]
FYI
https://github.com/iamseth/oracledb_exporter/pull/460

**Comment by Yannig** [comment]
Thanks for your PR. It's merged now. Will do a new release with this fix.
