### ISSUE TITLE
Need to display more than 2 values to the output in table format 

### ISSUE THREAD

**Issue by jayhima** [iamseth/oracledb_exporter#46]
We are planning to customize(.go) for our needs and would like to display multiple(fields) strings in the output using table format but we are getting the below error when we try to display that . can some one please help us to how to can add this functionality .go file to display more than 2 values in the grafana.

 **panic: inconsistent label cardinality: expected 2 label values but got 4 in []string{"STATUS", "!stdayofthe month", "sameday", "XXX"}**
like as shown below

XXX "1st day of the month" "someday" "Running"

Any help would be much appreciated.

**Comment by Yannig** [comment]
With last versions of exporter, you can use a toml file with custom requests.
Can you give me the request you wan't to use with expected result.

**Comment by Yannig** [comment]
I close the bug as there is no feedback to my question.
You can reopen it if you need it.
