### ISSUE TITLE
Special character password unable to connect

### ISSUE THREAD

**Issue by gameiro83** [iamseth/oracledb_exporter#47]
Hi,

I having trouble using a password that contains special characters like % . 

Error is always the same, even if I put the password in quotes or not:

`
Unable to connect to oracle:invalid URL escape "%m"  source=main.go:179'
`

Just need some help to make the connection work.

**Comment by frankYaohua** [comment]
If you do not have any variables to interpolate into your DATA_SOURCE_NAME variable, you can simply use single quota to avoid any interpolate.

[How to escape “!” and “&” in docker's environment varibles](https://superuser.com/questions/775173/how-to-escape-and-in-dockers-environment-varibles)

And if you want to connect as sysdba with special characters using docker:
docker run -d --name oracledb_exporter -p 9161:9161 -e 'DATA_SOURCE_NAME=sys:[you password]@[host]:[port]/[service name]?as=sysdba' iamseth/oracledb_exporter

Works for me.
