### ISSUE TITLE
When will PR#460 be released?

### ISSUE THREAD

**Issue by duj4** [iamseth/oracledb_exporter#484]
## What is the current behavior?
https://github.com/iamseth/oracledb_exporter/pull/460 has been merged on Jul 29th but the latest release is still on Apr 6th.

May I know when this fix will be released?

Thanks.

**Comment by duj4** [comment]
Any update on this issue?

**Comment by duj4** [comment]
hi @iamseth, may I have update on this question?

**Comment by Yannig** [comment]
Hi all. I will try to do a release during december.

**Comment by duj4** [comment]
> Hi all. I will try to do a release during december.

Thanks @Yannig for the reply

**Comment by gjrlopes** [comment]
Hi @Yannig @iamseth 

Is there any news about the new release?
Thanks

**Comment by Pawel-Gosek** [comment]
Hello @gjrlopes, please check this comment for your answer
https://github.com/iamseth/oracledb_exporter/issues/474#issuecomment-2634750922

**Comment by gjrlopes** [comment]
Thanks @Pawel-Gosek
