### ISSUE TITLE
Increase connect timeout value

### ISSUE THREAD

**Issue by andridzi** [iamseth/oracledb_exporter#49]
Hello

Is it possible to increase queryTimeout from 5 to 10 seconds?
https://github.com/iamseth/oracledb_exporter/blob/master/main.go#L30

Or may be make it as environment variable.

We have a big database and from time to time some queries are slow, and on output we are getting intermittent graphs in grafana

By the way, I have tried to build and image by myself and got the next error

```Step 15/29 : RUN go build -v -ldflags "-X main.Version=${VERSION} -s -w"
 ---> Running in 7f53a86f6a14
github.com/BurntSushi/toml
oracledb_exporter/vendor/github.com/mattn/go-oci8
# oracledb_exporter/vendor/github.com/mattn/go-oci8
vendor/github.com/mattn/go-oci8/oci8.go:4:17: fatal error: oci.h: No such file or directory
 #include <oci.h>
                 ^
compilation terminated.
oracledb_exporter/vendor/github.com/beorn7/perks/quantile
oracledb_exporter/vendor/github.com/golang/protobuf/proto
oracledb_exporter/vendor/github.com/prometheus/common/internal/bitbucket.org/ww/goautoneg
oracledb_exporter/vendor/github.com/prometheus/common/model
oracledb_exporter/vendor/github.com/prometheus/procfs
oracledb_exporter/vendor/github.com/Sirupsen/logrus
oracledb_exporter/vendor/github.com/prometheus/client_model/go
oracledb_exporter/vendor/github.com/matttproud/golang_protobuf_extensions/pbutil
oracledb_exporter/vendor/github.com/prometheus/common/log
oracledb_exporter/vendor/github.com/prometheus/common/expfmt
oracledb_exporter/vendor/github.com/prometheus/client_golang/prometheus
The command '/bin/sh -c go build -v -ldflags "-X main.Version=${VERSION} -s -w"' returned a non-zero code: 2```

Could you please help?

Thanks

**Comment by Yannig** [comment]
You can use `-query.timeout` option to change timeout value.

**Comment by andridzi** [comment]
Thanks Yannig!
I've already found it.
Sorry for disturbing.

**Comment by frankYaohua** [comment]
@andridzi Hi, sorry to bother, could I know how you set this -query.timeout option in docker? Thanks!

**Comment by andridzi** [comment]
hi @frankYaohua 
you can use --query.timeout argument
args:
  - '--query.timeout=20'

**Comment by frankYaohua** [comment]
Hi, @andridzi thanks for your reply! I really appreciate that. Could I know how you set that for docker? I mean set it in Dockerfile somewhere?

**Comment by andridzi** [comment]
hi @frankYaohua , it is not set in Dockerfile you have only ENTRYPOINT
ENTRYPOINT [ "/oracledb_exporter" ]
And then in kubernetes manifest or directly running docker container you just specifying an argument to an entrypoint, like '--query.timeout=20'
https://stackoverflow.com/questions/53543881/docker-run-pass-arguments-to-entrypoint

**Comment by frankYaohua** [comment]
@andridzi wow, I see! Thanks a lot! That is helpful!
