### ISSUE TITLE
can not start oracledb-exporer after add Custom metrics

### ISSUE THREAD

**Issue by lwlei** [iamseth/oracledb_exporter#57]
time="2019-09-27T11:39:10+08:00" level=info msg="Starting oracledb_exporter 0.2.3" source="main.go:337"
panic: interface conversion: interface {} is nil, not string

goroutine 36 [running]:
main.GeneratePrometheusMetrics(0xc000186240, 0xc0001642a0, 0xc0001c80d4, 0x39f, 0x0, 0x0)
        /home/travis/gopath/src/github.com/iamseth/oracledb_exporter/main.go:313 +0x6a0
main.ScrapeGenericValues(0xc000186240, 0xc0001b4180, 0xc000188710, 0xd, 0xc00018e400, 0x4, 0x4, 0xc000180f90, 0x0, 0x0, ...)
        /home/travis/gopath/src/github.com/iamseth/oracledb_exporter/main.go:260 +0x11d
main.ScrapeMetric(0xc000186240, 0xc0001b4180, 0xc000188710, 0xd, 0xc00018e400, 0x4, 0x4, 0xc000180f90, 0x0, 0x0, ...)
        /home/travis/gopath/src/github.com/iamseth/oracledb_exporter/main.go:216 +0xe8
main.(*Exporter).scrape(0xc0001686c0, 0xc0001b4180)
        /home/travis/gopath/src/github.com/iamseth/oracledb_exporter/main.go:189 +0x21a
main.(*Exporter).Collect(0xc0001686c0, 0xc0001b4180)
        /home/travis/gopath/src/github.com/iamseth/oracledb_exporter/main.go:145 +0x3c
main.(*Exporter).Describe(0xc0001686c0, 0xc000168720)
        /home/travis/gopath/src/github.com/iamseth/oracledb_exporter/main.go:137 +0xb0
github.com/iamseth/oracledb_exporter/vendor/github.com/prometheus/client_golang/prometheus.(*registry).Register.func1(0x7ebf80, 0xc0001686c0, 0xc000168720)
        /home/travis/gopath/src/github.com/iamseth/oracledb_exporter/vendor/github.com/prometheus/client_golang/prometheus/registry.go:218 +0x3b
created by github.com/iamseth/oracledb_exporter/vendor/github.com/prometheus/client_golang/prometheus.(*registry).Register
        /home/travis/gopath/src/github.com/iamseth/oracledb_exporter/vendor/github.com/prometheus/client_golang/prometheus/registry.go:217 +0xa2

**Comment by lwlei** [comment]
[[metric]]
context = "UserSessionV2"
labels = [ "username", "machine", "program", "module" ]
metricsdesc = { value= "Gauge metric with count of user sessions by username,machine,program and module." }
request = '''
  SELECT username,
    CASE
      WHEN instr(machine, '.') > 0 THEN substr(machine, 1, instr(machine, '.') - 1)
      WHEN instr(machine, '\') > 0 THEN replace(machine, '\', '-')
      ELSE machine
      END AS machine,
    program,module,COUNT(*) AS ses_num
  FROM v$session
  WHERE username IS NOT NULL
  AND substr(machine, 1, 25) <> 'WORKGROUP\TRAVELSK-XXOC2D'
  GROUP BY username, machine, program, module
  UNION ALL
  SELECT username,
    CASE
      WHEN instr(substr(machine, 1, 25), '.') > 0 THEN substr(substr(machine, 1, 25), 1, instr(substr(machine, 1, 25), '.') - 1)
      WHEN instr(substr(machine, 1, 25), '\') > 0 THEN replace(substr(machine, 1, 25), '\', '-')
      ELSE substr(machine, 1, 25)
      END AS machine,
      program, module, COUNT(*) AS ses_num
  FROM v$session
  WHERE username IS NOT NULL
  AND substr(machine, 1, 25) = 'WORKGROUP\TRAVELSK-XXOC2D'
  GROUP BY username, machine, program, module
'''

**Comment by hartman17** [comment]
When I see this error it's typically due to a null value returned in the select statement.  I'd double check that your select is returning data in every column in all the rows returned from the database.

**Comment by lwlei** [comment]
Yes, thanks. I have tried to use NVL function to replace null values and it works well.
