### ISSUE TITLE
"Error scraping for server_session : No metrics found while parsing - COUNT

### ISSUE THREAD

**Issue by tmihaldinec** [iamseth/oracledb_exporter#58]
Hi,
i see that this error is common and sql response should be integer.. but i am doing count. which is number and therefore integer

this is metric config

[[metric]]
context = "server_session"
labels = [ "server_1" ]
request = "select count(case when machine ='server01' then 1 end) as server_1 from  v$session WHERE TYPE <> 'BACKGROUND'"
metricsdesc = { server_1 = "Session on server01" }
metricstype = { server_1 = "counter" }

if i do plain select count(*) from v$session it looks fine

thanks
tomislav

**Comment by tmihaldinec** [comment]
Hi,
is there anyone who can help here? 

thanks
tomislav

**Comment by Yannig** [comment]
Can you provide logs from the exporter?

**Comment by tmihaldinec** [comment]
HI

[root@lvpapm01 oracledb_exporter.0.2.3.linux-amd64]# ./oracledb_exporter -default.metrics test.toml -query.timeout 90 -log.level debug -log.format logger:stdout?json=true
{"level":"info","msg":"Starting oracledb_exporter 0.2.3","source":"main.go:337","time":"2019-11-25T22:21:15+01:00"}
{"level":"error","msg":"Error scraping for siebel_server_session : No metrics found while parsing","source":"main.go:190","time":"2019-11-25T22:21:15+01:00"}
{"level":"info","msg":"Listening on :9161","source":"main.go:359","time":"2019-11-25T22:21:15+01:00"}
{"level":"error","msg":"Error scraping for siebel_server_session : No metrics found while parsing","source":"main.go:190","time":"2019-11-25T22:21:16+01:00"}
{"level":"error","msg":"Error scraping for siebel_server_session : No metrics found while parsing","source":"main.go:190","time":"2019-11-25T22:21:31+01:00"}

cat test.toml 
[[metric]]
context = "test_server_session"
labels = [ "lvpserver1" ]
request = "SELECT COUNT (case when machine ='lvpserver1.test.local' then 1 end) as lvpserver1 from v$session HAVING COUNT (machine) > 1"
metricsdesc = { lvpserver1 = "Session on lvpserver1" }
metricstype = { lvpserver1 = "counter" }


but when i do this same query manually..

[root@lvpapm01 oracledb_exporter.0.2.3.linux-amd64]# sqlplus monitor/monitorXXX@DBSERVER.test.local:1810/TEST

SQL*Plus: Release 19.0.0.0.0 - Production on Mon Nov 25 22:19:18 2019
Version 19.3.0.0.0

Copyright (c) 1982, 2019, Oracle.  All rights reserved.

Last Successful login time: Mon Nov 25 2019 22:17:31 +01:00

Connected to:
Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit Production
With the Partitioning, OLAP, Advanced Analytics and Real Application Testing options

SQL> SELECT COUNT (case when machine ='vpserver1.test.local' then 1 end) as vpserver1 from v$session HAVING COUNT (machine) > 1
  2  ;

 vpserver1
----------
        89

to me this looks like exporter see integer response as non-integer

thanks
tomislav

**Comment by Yannig** [comment]
I think the problem is that you are trying to populate a label with the counter.

Can you try again using this request:

```
[[metric]]
context = "test_server_session"
labels = [ "machine" ]
request = "SELECT COUNT (case when machine ='lvpserver1.test.local' then 1 end) as session_count, machine from v$session HAVING COUNT (machine) > 1"
metricsdesc = { session_count = "Session count" }
metricstype = { session_count = "counter" }
```

**Comment by tmihaldinec** [comment]
Hi

this query returns
ORA-00937: not a single-group group function

t.

**Comment by Yannig** [comment]
It was an example to help you to understand that you need to have a field to count your session and another for your label.

You can have a look at the various examples in the repo but I cannot help you to do that:

https://github.com/iamseth/oracledb_exporter/blob/master/default-metrics.toml
