### ISSUE TITLE
./oracledb_exporter: error while loading shared libraries: libclntsh.so.18.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by zhangshengdong** [iamseth/oracledb_exporter#61]
My Oracle version is 11.2.0.4。when I execute the command below：
[oracle@db oracledb_exporter.0.2.2.linux-amd64]$ ./oracledb_exporter 
i found below information:
./oracledb_exporter: error while loading shared libraries: libclntsh.so.18.1: cannot open shared object file: No such file or directory

and my lib  below：
[root@db opt]# find / -name libclntsh.*
/tmp/OraInstall2017-05-15_10-41-31AM/ext/lib/libclntsh.so.11.1
/u01/app/product/11.2.0/db_1/inventory/backup/2017-05-15_10-41-43AM/Scripts/ext/lib/libclntsh.so.11.1
/u01/app/product/11.2.0/db_1/inventory/Scripts/ext/lib/libclntsh.so.11.1
/u01/app/product/11.2.0/db_1/lib/libclntsh.so
/u01/app/product/11.2.0/db_1/lib/libclntsh.so.10.1
/u01/app/product/11.2.0/db_1/lib/libclntsh.so.11.1

**Comment by anishshaw** [comment]
I too found the same issue, whereas I can see that file is present on my server.
[root@seliicbl01060 user]# /root/prometheus/oracledb_exporter.0.2.2.linux-amd64/oracledb_exporter -l log.level debug -l web.listen-address 9161
/root/prometheus/oracledb_exporter.0.2.2.linux-amd64/oracledb_exporter: error while loading shared libraries: libclntsh.so.18.1: cannot open shared object file: No such file or directory

[root@seliicbl01060 user]# find / -name libclntsh\* -ls 2>/dev/null
536871462 76368 -rwxr-xr-x   1 root     root     78200832 Feb 26  2019 /usr/lib/oracle/18.5/client64/lib/libclntsh.so.18.1
536871463 8164 -rwxr-xr-x   1 root     root      8357160 Feb 26  2019 /usr/lib/oracle/18.5/client64/lib/libclntshcore.so.18.1
109193783 7848 -rwxr-x---   1 oracle   dba       8033199 Apr 12  2019 /opt/oracle/product/12gr2/db/inventory/Scripts/ext/lib/libclntshcore.so.12.1
109193786 69960 -rwxr-x---   1 oracle   dba      71638263 Apr 12  2019 /opt/oracle/product/12gr2/db/inventory/Scripts/ext/lib/libclntsh.so.12.1
511713792 7848 -rw-r-----   1 oracle   dba       8033199 Apr 12  2019 /opt/oracle/product/12gr2/db/inventory/backup/2019-04-12_06-58-35PM/Scripts/ext/lib/libclntshcore.so.12.1
511713795 69960 -rw-r-----   1 oracle   dba      71638263 Apr 12  2019 /opt/oracle/product/12gr2/db/inventory/backup/2019-04-12_06-58-35PM/Scripts/ext/lib/libclntsh.so.12.1
251662958    0 lrwxrwxrwx   1 oracle   dba            17 Apr 12  2019 /opt/oracle/product/12gr2/db/lib/libclntsh.so -> libclntsh.so.12.1
251814403 7848 -rwxr-xr-x   1 oracle   dba       8033608 Apr 12  2019 /opt/oracle/product/12gr2/db/lib/libclntshcore.so.12.1
251814406 69964 -rwxr-xr-x   1 oracle   dba      71640160 Apr 12  2019 /opt/oracle/product/12gr2/db/lib/libclntsh.so.12.1
251814408    0 lrwxrwxrwx   1 oracle   dba            12 Apr 12  2019 /opt/oracle/product/12gr2/db/lib/libclntsh.so.10.1 -> libclntsh.so
251814409    0 lrwxrwxrwx   1 oracle   dba            12 Apr 12  2019 /opt/oracle/product/12gr2/db/lib/libclntsh.so.11.1 -> libclntsh.so
251658785    0 lrwxrwxrwx   1 oracle   dba            21 Apr 12  2019 /opt/oracle/product/12gr2/db/lib/libclntshcore.so -> libclntshcore.so.12.1

As per pre-requisite I installed Oracle basic instant client 18.5 (earlier I installed 19.3 version but as per thrown error seems it was looking for 18.x version hence downgraded to 18.5, Still the same error)

**Comment by daveram** [comment]
Same issue here, tried setting LD_LIBRARY_PATH and even sticking the exporter binary in the same path as the instant client, no luck.  Found another oracle exporter below I'll try using next to see if it fairs any better
https://github.com/freenetdigital/prometheus_oracle_exporter

**Comment by Yannig** [comment]
I'm working on a release with several supported versions of Oracle libraries. But even in this case, the version used is anyway too old (11g).

Thanks @daveram for your answer.

**Comment by Duks03** [comment]
I observed that differnet version of Oracle basic instant client will have libclntsh.so.{version}.{sub-version} . **Can any one please help me to understand why oracledb_exporter is asking only for only for libclntsh.so.18.1?** I am using oracle client 12.1 for one of my old project and had same issue. I created  libclntsh.so.18.1 symbolic link file to point libclntsh.so.12.1 which is working for me.  Still little curious about this behaviour. Thanks :-)

**Comment by Yannig** [comment]
Programs written in go are static. Unfortunately, the Oracle lib forbids doing so. Therefore it remains an external dependency. Another problem, the lib file change is name with each release. Hence the symbolic link to make.

But another solution exists: use a Docker image. In this case, the exporter embarks dependencies and you no longer have to worry.

**Comment by packergundo** [comment]
I'm seeing that issue while using the docker image....

**Comment by Yannig** [comment]
There's a problem in value of the LD_LIBRARY_PATH.

To workaround this issue, you can run the exporter by exporting this:

    docker run -it -e LD_LIBRARY_PATH=/usr/lib/oracle/18.5/client64/lib iamseth/oracledb_exporter:0.2.5

**Comment by packergundo** [comment]
I also found that 0.2.3. worked without that error, and thank you for that prompt update.

**Comment by Yannig** [comment]
I have released version 0.2.6a to fix this issue.

**Comment by m934030039** [comment]
Hi Yanning,

    I am using your oracledb_exporter 0.2.6a but I got same issue.
  
     I am not using Docker but an physical HW server with Oracle 12.2.0 (Red Hat Enterprise Linux Server release 6.9 (Santiago)) 

NOTE:  we must use Oracle 12.2.0

[oracledb_exporter.0.2.6a-ora18.5.linux-amd64]# ./oracledb_exporter
./oracledb_exporter: error while loading shared libraries: libclntsh.so.18.1: cannot open shared object file: No such file or directory

Many thanks,

-Sheng

**Comment by Yannig** [comment]
The problem here is that you are trying to use an Oracle client with very recent binaries (version 18.xxx) with an old Oracle base version (12c). To get around the problem, you have to install the binaries of 18 next to those of 12c.
The easiest way - by far - is to launch the exporter using Docker. This way, you will no longer have these dependencies problems.

**Comment by m934030039** [comment]
Hello Sir,

     >To get around the problem, you have to install the binaries of 18
next to those of 12c.

I have no idea about DB so please help to clarify below

Do you mean to install Oracle Client 18 ?
Can 18 and 12c co-exist?
Will 28 impact to 12c?

The server is running on Prod so I have to be very careful about the next
action.

Once I resolve the issue, I will provide step by step for new comer.

I gotta go to sleep now.

-Sheng

**Comment by Yannig** [comment]
If you are not sure what to do, nothing prevents you from using an exporter that is on another machine (running with Docker for example). Thus, no modification to be made on the production server.

**Comment by chabater** [comment]
i have same issue on oracle version 1.12 , i try to link libclntsh.so.18.1 to /ora_sys/app/db12c/lib/libclntsh.so.18.1 , but it still error on oracledb_exporter[66102] : /root/oracledb_exporter.0.2.9-ora18.5.linux-amd64/oracledb_exporter: error while loading shared libraries: libclntsh.so.18.1: cannot open shared object file: No such file or directory
