### ISSUE TITLE
Anyway to limit or control the metrics collection time?

### ISSUE THREAD

**Issue by mzs114** [iamseth/oracledb_exporter#63]
Hi,

I don't know how often does the exporter run the queries against the DB, is it like every minute, five minutes, etc.
I am asking as the use case is like, we may not want to metrics that often and some more often.
Is it possible to explicitly configure this somewhere?

Please excuse my question(or my lack of Prometheus way)  as I am coming from ELK and metricbeat, where the metrics generation interval can be set for each module(exporter) and I am using this exporter for just Oracle DB.

**Comment by Yannig** [comment]
Hi,

Prometheus use a pull mecanism to scrape values. This configuration have to be done in Prometheus. This exporter is unable to configure this frequency.

Regards

**Comment by Yannig** [comment]
This can be done global:

```
global:
  # How frequently to scrape targets by default.
  [ scrape_interval: <duration> | default = 1m ]
```

Or on job definition :

```
job_name: oracle-exporter
scrape_interval: 10s
```

**Comment by mzs114** [comment]
So how often does the oracle exporter run the query against the DB?
What is the default value?

**Comment by Yannig** [comment]
Each time you call the metrics endpoint.
