### ISSUE TITLE
can't get the ORACLE fra information

### ISSUE THREAD

**Issue by wongcao** [iamseth/oracledb_exporter#65]
Hi all,
I can't get the ORACLE fra information.But if I replace v$flash_recovery_area_usage with v$session, it works.

default-metrics.toml
[[metric]]
context = "test"
metricsdesc = { value = "oracle fra" }
request = "select sum(percent_space_used) as value from v$flash_recovery_area_usage"

[[metric]]
context = "test1"
metricsdesc = { value = "oracle fra" }
request = "select count(0) as value from v$flash_recovery_area_usage"

error.log
{"level":"error","msg":"Error scraping for test : No metrics found while parsing","source":"main.go:190","time":"2019-11-27T16:32:12+08:00"}
{"level":"error","msg":"Error scraping for test1 : No metrics found while parsing","source":"main.go:190","time":"2019-11-27T16:32:12+08:00"}

$ echo $DATA_SOURCE_NAME 
dbmon/XXXXXXXXXX@test
$ sqlplus dbmon/XXXXXXXXXX@test

SQL*Plus: Release 11.2.0.4.0 Production on Wed Nov 27 16:38:52 2019

Copyright (c) 1982, 2013, Oracle.  All rights reserved.

Connected to:
Oracle Database 11g Enterprise Edition Release 11.2.0.4.0 - 64bit Production
With the Partitioning, OLAP, Data Mining and Real Application Testing options

SQL> select sum(percent_space_used) as value from v$flash_recovery_area_usage;

     VALUE
----------
      9.36

SQL> select count(0) as value from v$flash_recovery_area_usage;

     VALUE
----------
	 7

**Comment by Yannig** [comment]
I'm wondering if the problem may come from the float value. Can you multiply by 100 and convert the result to int?

**Comment by wongcao** [comment]
I tried everything you said,and it didn't work.
And why count v$session is OK,but count v$flash_recovery_area_usage dosen't work

**Comment by Yannig** [comment]
Can you try the master version? There's a new log message to know what's going on when parsing value.

**Comment by Yannig** [comment]
This code is released with version 0.2.4.
