### ISSUE TITLE
No metrics found while parsing" source="main.go:190"

### ISSUE THREAD

**Issue by zangqianglei** [iamseth/oracledb_exporter#66]
[[metric]]
context = "recovery_file_dest"
labels = [ "name" ]
metricsdesc = { bytes="recovery dest total size",usebytes="used sizes",reusebytes="reclaime size" }
request = '''
SELECT t.NAME as "name",
       decode(t.SPACE_LIMIT, 0, '-1', t.SPACE_LIMIT) as "bytes",
       decode(t.SPACE_USED, 0, '-1', t.SPACE_USED) as "usebytes",
       decode(t.SPACE_RECLAIMABLE, 0, '-1', t.SPACE_RECLAIMABLE) as "reusebytes"
  from v$recovery_file_dest t
'''

**Comment by octosith** [comment]
I have the same problem
`INFO[0000] Starting oracledb_exporter 0.2.3              source=main.go:337
ERRO[0001] Error scraping for query : No metrics found while parsing  source=main.go:190
INFO[0001] Listening on :9162                            source=main.go:359
`
[[metric]]
context = "query"
request = "SELECT oi.status as status, COUNT(1) as count FROM object_info oi, cad_qual_dev.v$_onew_request_status v WHERE v.code = oi.status AND oi.date_registration >= trunc(sysdate) AND oi.address_code IN ('0.0.4.5','0.0.3.3') AND oi.kind = 2 GROUP BY oi.status ORDER BY oi.status"
metricdesc = { status = "first column value", count = "Second column value" }

**Comment by frankYaohua** [comment]
Same problem for me.

**Comment by Yannig** [comment]
The last version of the exporter (0.2.4) give more informations.
Can you give it a try?

**Comment by zangqianglei** [comment]
> The last version of the exporter (0.2.4) give more informations.
> Can you give it a try?

thanks,do you have Pre-compiled versions for Linux 64 bit?

**Comment by zangqianglei** [comment]
> The last version of the exporter (0.2.4) give more informations.
> Can you give it a try?

Solved my problem！thanks

**Comment by Yannig** [comment]
Nice !
