### ISSUE TITLE
The parameter web.listen-address has some problem. Is this a bug?

### ISSUE THREAD

**Issue by SFHfeihong** [iamseth/oracledb_exporter#67]
`[root@gujp-server0005 oracledb_exporter.0.2.3.linux-amd64]# ./oracledb_exporter -log.level=debug -query.timeout=15 -web.listen-address=9162

INFO[0000] Starting oracledb_exporter 0.2.3              source=main.go:337

INFO[0000] Listening on 9162                             source=main.go:359

FATA[0000] listen tcp: address 9162: missing port in address  source=main.go:360
`

If I delete the parameter web.listen-address, it works fine.
`[root@gujp-server0005 oracledb_exporter.0.2.3.linux-amd64]# ./oracledb_exporter -log.level=debug -query.timeout=15

INFO[0000] Starting oracledb_exporter 0.2.3              source=main.go:337

INFO[0000] Listening on :9161                            source=main.go:359
`

**Comment by pppoke** [comment]
> `[root@gujp-server0005 oracledb_exporter.0.2.3.linux-amd64]# ./oracledb_exporter -log.level=debug -query.timeout=15 -web.listen-address=9162
> 
> INFO[0000] Starting oracledb_exporter 0.2.3 source=main.go:337
> 
> INFO[0000] Listening on 9162 source=main.go:359
> 
> FATA[0000] listen tcp: address 9162: missing port in address source=main.go:360
> `
> 
> If I delete the parameter web.listen-address, it works fine.
> `[root@gujp-server0005 oracledb_exporter.0.2.3.linux-amd64]# ./oracledb_exporter -log.level=debug -query.timeout=15
> 
> INFO[0000] Starting oracledb_exporter 0.2.3 source=main.go:337
> 
> INFO[0000] Listening on :9161 source=main.go:359
> `

I got the same problem，Someone help?
