### ISSUE TITLE
The parameter web.listen-address works wrong. Is this a bug?

### ISSUE THREAD

**Issue by SFHfeihong** [iamseth/oracledb_exporter#68]
`[root@gujp-server0005 oracledb_exporter.0.2.3.linux-amd64]# ./oracledb_exporter -log.level=debug -query.timeout=15 -web.listen-address=9162

INFO[0000] Starting oracledb_exporter 0.2.3 source=main.go:337

INFO[0000] Listening on 9162 source=main.go:359

FATA[0000] listen tcp: address 9162: missing port in address source=main.go:360
`

If I delete the parameter web.listen-address, it works fine.
`[root@gujp-server0005 oracledb_exporter.0.2.3.linux-amd64]# ./oracledb_exporter -log.level=debug -query.timeout=15

INFO[0000] Starting oracledb_exporter 0.2.3 source=main.go:337

INFO[0000] Listening on :9161 source=main.go:359
`

**Comment by SFHfeihong** [comment]
It should be ：9162.

**Comment by pppoke** [comment]
> It should be ：9162.

Yes,Thx
