### ISSUE TITLE
cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by shinehertheway** [iamseth/oracledb_exporter#70]
When I start oracle_export, the error is as follows：
./oracledb_exporter: error while loading shared libraries: libclntsh.so.18.1: cannot open shared object file: No such file or directory
I don't know what the version of this library has to do with our plugin. The oracle version of all my servers is 11g.Can you provide an idea? Because first time using it.

**Comment by Yannig** [comment]
The exporter use libraries from Oracle to work.
Here, you operate an old version of Oracle (11g) with a binary compiled against lib from Oracle 18.1.
You can have a look at libclntsh.so.* file and try to simlink libclntsh.so.18.1 against it.
A better workaround should be to use Docker to launch the exporter.
