### ISSUE TITLE
panic: interface conversion: interface {} is nil, not string

### ISSUE THREAD

**Issue by zangqianglei** [iamseth/oracledb_exporter#71]
[root@rac1 oracledb_exporter]# /usr/local/oracledb_exporter/oracledb_exporter -default.metrics /usr/local/oracledb_exporter/default-metrics.toml
INFO[0000] Starting oracledb_exporter 0.2.3              source=main.go:337
panic: interface conversion: interface {} is nil, not string

goroutine 20 [running]:
main.GeneratePrometheusMetrics(0xc00018a180, 0xc0001a1320, 0xc0001ac4b0, 0x1d1, 0x0, 0x0)
	/home/travis/gopath/src/github.com/iamseth/oracledb_exporter/main.go:313 +0x6a0
main.ScrapeGenericValues(0xc00018a180, 0xc0001c0120, 0xc00018cf10, 0x8, 0x0, 0x0, 0x0, 0xc0001e4d50, 0x0, 0x0, ...)
	/home/travis/gopath/src/github.com/iamseth/oracledb_exporter/main.go:260 +0x11d
main.ScrapeMetric(0xc00018a180, 0xc0001c0120, 0xc00018cf10, 0x8, 0x0, 0x0, 0x0, 0xc0001e4d50, 0x0, 0x0, ...)
	/home/travis/gopath/src/github.com/iamseth/oracledb_exporter/main.go:216 +0xe8
main.(*Exporter).scrape(0xc0001a0d80, 0xc0001c0120)
	/home/travis/gopath/src/github.com/iamseth/oracledb_exporter/main.go:189 +0x21a
main.(*Exporter).Collect(0xc0001a0d80, 0xc0001c0120)
	/home/travis/gopath/src/github.com/iamseth/oracledb_exporter/main.go:145 +0x3c
main.(*Exporter).Describe(0xc0001a0d80, 0xc0001a0de0)
	/home/travis/gopath/src/github.com/iamseth/oracledb_exporter/main.go:137 +0xb0
github.com/iamseth/oracledb_exporter/vendor/github.com/prometheus/client_golang/prometheus.(*registry).Register.func1(0x7ebf80, 0xc0001a0d80, 0xc0001a0de0)
	/home/travis/gopath/src/github.com/iamseth/oracledb_exporter/vendor/github.com/prometheus/client_golang/prometheus/registry.go:218 +0x3b
created by github.com/iamseth/oracledb_exporter/vendor/github.com/prometheus/client_golang/prometheus.(*registry).Register
	/home/travis/gopath/src/github.com/iamseth/oracledb_exporter/vendor/github.com/prometheus/client_golang/prometheus/registry.go:217 +0xa2

**Comment by Yannig** [comment]
I am sorry but this request does not meet the standards necessary to be studied. Please provide at least the following informations:
- Exporter version
- Oracle database version
- System information (Kernel version, distribution etc.)

On the other hand, this place is not a forum to learn how to operate an Oracle database.

**Comment by zwunix** [comment]
I have meet this problem too. How can i do？

**Comment by zwunix** [comment]
panic: interface conversion: interface {} is nil, not string

goroutine 8 [running]:
main.GeneratePrometheusMetrics(0xc000100240, 0xc000156120, 0xc00001e320, 0x98, 0x0, 0x0)
	/home/travis/gopath/src/github.com/iamseth/oracledb_exporter/main.go:313 +0x6a0
main.ScrapeGenericValues(0xc000100240, 0xc0000745a0, 0xc000016ff0, 0x8, 0x0, 0x0, 0x0, 0xc0001794a0, 0x0, 0x0, ...)
	/home/travis/gopath/src/github.com/iamseth/oracledb_exporter/main.go:260 +0x11d
main.ScrapeMetric(0xc000100240, 0xc0000745a0, 0xc000016ff0, 0x8, 0x0, 0x0, 0x0, 0xc0001794a0, 0x0, 0x0, ...)
	/home/travis/gopath/src/github.com/iamseth/oracledb_exporter/main.go:216 +0xe8
main.(*Exporter).scrape(0xc0000116e0, 0xc0000745a0)
	/home/travis/gopath/src/github.com/iamseth/oracledb_exporter/main.go:189 +0x21a
main.(*Exporter).Collect(0xc0000116e0, 0xc0000745a0)
	/home/travis/gopath/src/github.com/iamseth/oracledb_exporter/main.go:145 +0x3c
main.(*Exporter).Describe(0xc0000116e0, 0xc000011740)
	/home/travis/gopath/src/github.com/iamseth/oracledb_exporter/main.go:137 +0xb0
github.com/iamseth/oracledb_exporter/vendor/github.com/prometheus/client_golang/prometheus.(*registry).Register.func1(0x7ebf80, 0xc0000116e0, 0xc000011740)
	/home/travis/gopath/src/github.com/iamseth/oracledb_exporter/vendor/github.com/prometheus/client_golang/prometheus/registry.go:218 +0x3b
created by github.com/iamseth/oracledb_exporter/vendor/github.com/prometheus/client_golang/prometheus.(*registry).Register
	/home/travis/gopath/src/github.com/iamseth/oracledb_exporter/vendor/github.com/prometheus/client_golang/prometheus/registry.go:217 +0xa2
