### ISSUE TITLE
Support of user "sys as sysdba" 

### ISSUE THREAD

**Issue by kostoww** [iamseth/oracledb_exporter#72]
Hello, 
the exporter seems to be great, but in my case, I have to connect with user "sys as sysdba" which is difficult with a docker container. 
Can you share some idea on how to work around this? 
Thanks!

**Comment by Yannig** [comment]
Well, the problem came from the underlying lib we use to scrape metrics.
You can have a look at this issue to a better understanding: https://github.com/iamseth/oracledb_exporter/issues/48

PR are welcome
