### ISSUE TITLE
"level":"error","msg":"Error scraping for wait_time : ORA-00942: table or view does not exist\n","source":"main.go:188","time":

### ISSUE THREAD

**Issue by xinghailin** [iamseth/oracledb_exporter#73]

**Comment by Yannig** [comment]
I am sorry but this request does not meet the standards necessary to be studied. Please provide at least the following informations:
- Exporter version
- Oracle database version
- System information (Kernel version, distribution etc.)

On the other hand, this place is not a forum to learn how to operate an Oracle database.
