### ISSUE TITLE
Error scraping for tablespace : ORA-00942: table or view does not exist\n","source":"main.go:188

### ISSUE THREAD

**Issue by xinghailin** [iamseth/oracledb_exporter#74]

**Comment by xinghailin** [comment]
I can't find the reason for this error

**Comment by Yannig** [comment]
I am sorry but this request does not meet the standards necessary to be studied. Please provide at least the following informations:
- Exporter version
- Oracle database version
- System information (Kernel version, distribution etc.)

On the other hand, this place is not a forum to learn how to operate an Oracle database.
