### ISSUE TITLE
How do I verify that oracledb_exporter is connected to the database

### ISSUE THREAD

**Issue by xinghailin** [iamseth/oracledb_exporter#75]
How do I verify that oracledb_exporter is connected to the database

**Comment by Yannig** [comment]
I am sorry but this request does not meet the standards necessary to be studied. Please provide at least the following informations:
- Exporter version
- Oracle database version
- System information (Kernel version, distribution etc.)

On the other hand, this place is not a forum to learn how to operate an Oracle database.
