### ISSUE TITLE
dashboards

### ISSUE THREAD

**Issue by davidkarlsen** [iamseth/oracledb_exporter#8]
Hi - do you have any dashboards for grafana laying around - could maybe be checked in and follow the code and/or shared at grafana.net ?

**Comment by iamseth** [comment]
I don't, sorry. If you come up with one, please send a PR.

**Comment by Keleir** [comment]
@davidkarlsen  Here is what you want: https://grafana.com/dashboards/3333

**Comment by iamseth** [comment]
thank you @Keleir

**Comment by xuanyuanaosheng** [comment]
Could you please add the grafana json file to the Repo?  May be it is time to update the grafana dashboard.
