### ISSUE TITLE
could not connect RAC

### ISSUE THREAD

**Issue by SaitorSan** [iamseth/oracledb_exporter#80]
Hello
When I connect to RAC database, It doesn't works. The log file just print (time="2020-01-07T14:58:13+08:00" level=info msg="Starting oracledb_exporter 0.2.3" source="main.go:337") and then nothing else. If connect to other database, It works well.

**Comment by Yannig** [comment]
I don't have RAC instance available to test your problem.
Maybe the RAC instance use a different listener (on a different port).
