### ISSUE TITLE
Exporter does not start after crash/reboot

### ISSUE THREAD

**Issue by Justaris** [iamseth/oracledb_exporter#81]
Hello everyone, 
We have been using v0.8 but we had to upgrade to v2.2 because of ping/reconnect ability. 
After that, exporter does not start automatically after reboot/crash. Updated service file, tried different solutions for it but no luck.

Can anyone help with it?

**Comment by Yannig** [comment]
Can you try to use the last version (0.2.4?) and give me some feedback.

**Comment by voskampm** [comment]
Any errors in the syslog? What happens if you start the exporter manually? Does that work? Any errors?
