### ISSUE TITLE
Error pinging oracle: empty DSN

### ISSUE THREAD

**Issue by gengxinyu0** [iamseth/oracledb_exporter#82]
When I was using oracledb_exporter, I started Error pinging oracle: empty DSN. I didn't find a good solution. I hope it can be solved

**Comment by gengxinyu0** [comment]
Can someone help me

**Comment by Yannig** [comment]
Did you have exported DATA_SOURCE_NAME variable in your env ?
Something like this:

DATA_SOURCE_NAME=user/pass@oracle-host/oracle-sid

**Comment by gengxinyu0** [comment]
Yes I correctly configured the Oracle environment variable

**Comment by Yannig** [comment]
Did you export the env var ? (ie export DATA_SOURCE_NAME=blabla)

You can have a look at this location: https://github.com/mattn/go-oci8/blob/master/oci8.go#L42

**Comment by gengxinyu0** [comment]
Thank you very much for your answer

**Comment by checho13cadc** [comment]
@gengxinyu0 Your problem was solved? I have the same problem, what do you did for fix this ?

**Comment by gengxinyu0** [comment]
This problem has not been solved. I am also looking for a solution. I hope to get your help


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"checho13cadc"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月12日(星期四) 凌晨2:55
收件人:&nbsp;"iamseth/oracledb_exporter"<oracledb_exporter@noreply.github.com&gt;;
抄送:&nbsp;"𓆡𓆝𓆟𓆜𓆞𓆝𓆟𓆜𓆞"<1287947427@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [iamseth/oracledb_exporter] Error pinging oracle: empty DSN (#82)





 
@gengxinyu0 Your problem was solved? I have the same problem, what do you did for fix this ?

**Comment by checho13cadc** [comment]
@gengxinyu0 I solved this problem, in file /etc/systemd/system/oracle_exporter.service I have teh next lines:

[Unit]
Description=Prometheus Node Exporter
Wants=network-online.target
After=network-online.target

[Service]
Environment="DATA_SOURCE_NAME=user/password@server:port/NAME_SERVICE_DB"
User=oracle
Group=oinstall
Type=simple
ExecStart=/usr/local/bin/oracledb_exporter -default.metrics /opt/default-metrics.toml -log.level error -web.listen-address :9161

[Install]
WantedBy=multi-user.target

**Comment by JesusFrontelo** [comment]
Hi @checho13cadc, 
Thanks for your answer. 
That solves if you only had one database, but how can it be done for multiple databases?
