### ISSUE TITLE
Binaries are missing for release 0.2.4

### ISSUE THREAD

**Issue by voskampm** [iamseth/oracledb_exporter#83]
Hi,

Binaries are missing for release 0.2.4 in https://github.com/iamseth/oracledb_exporter/releases. Could you fix that or give a pointer to instructions for compiling the source code.

Regards,

Michiel

**Comment by zangqianglei** [comment]
I compile binary package by myself, you try
[](https://github.com/zangqianglei/oracledb_exporter/releases)

**Comment by zangqianglei** [comment]
I compile binary package by myself, you try
https://github.com/zangqianglei/oracledb_exporter/releases

**Comment by voskampm** [comment]
I did some research:  Below the procedure to create a binary for Linux
* git clone https://github.com/iamseth/oracledb_exporter
* cd oracledb_exporter
* Edit Makefile: Bump VERSION to 0.2.4.
* Edit the Dockerfile. Replace ENTRYPOINT ["/oracledb_exporter"] with CMD ["/oracledb_exporter"]
* Build a new image and start the container
  make
  make ubuntu-image
  docker run -i -t iamseth/oracledb_exporter:latest /bin/bash
* From another shell
** Find the ID of the new container
 docker ps
** Copy to binary to your local disk 
 docker cp 2bc014e6b2bc:/oracledb_exporter .

**Comment by voskampm** [comment]
Accidentally closed the issue. Binaries are still missing.

**Comment by Yannig** [comment]
The binary have now a different name. I'll try to fix that when i can.

**Comment by Yannig** [comment]
Bin are available with last version (0.2.5).
