### ISSUE TITLE
Connection terminates immediately

### ISSUE THREAD

**Issue by packergundo** [iamseth/oracledb_exporter#85]
0.2.5 terminates the connection immediately, preventing a metric scrape

**Comment by packergundo** [comment]
telnet localhost 9161
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
Connection closed by foreign host.

**Comment by packergundo** [comment]
Timeout issues on the metrics and on raw connections. Thought it was resolved and I was reacting too early, but I think it is an issue.

**Comment by Yannig** [comment]
What scrapper are you using? Bin or docker?
You can set timeout connection using QUERY_TIMEOUT env variable. By default, the value is set to 5 seconds which - I think - is already quite good enough.
