### ISSUE TITLE
Oracle Database Tablespace Value Conversion Issue 

### ISSUE THREAD

**Issue by TanveerMujtaba** [iamseth/oracledb_exporter#87]
Getting following error upon starting the oracle exporter:

ERRO[1189] Unable to convert current value to float (metric=limit_value,metricHelp=Generic counter metric from v$resource_limit view in Oracle (limit value).,value=< UNLIMITED>)  source=main.go:245
ERRO[1194] Error scraping for tablespace : Oracle query timed out  source=main.go:198

Kindly help me to resolve this issue. 
Oracle Exporter Version: 0.2.6a
Oracle Client: 12.1

**Comment by Yannig** [comment]
Here, the exporter doesn't understand the value "UNLIMITED". So you have to replace it with something else in your SQL request.
Values must be an integer or float. Others things aren't  supported.

**Comment by TanveerMujtaba** [comment]
Hi Team

Can I configure this plugin for multiple oracle databases ? If yes, how to configure it.

Regards
Tanveer Mujtaba K



Sensitivity: Internal & Restricted

**Comment by Yannig** [comment]
No you can't. You have to launch the exporter multiple times.
