### ISSUE TITLE
Error pinging oracle: ORA-12162: TNS:net service name is incorrectly specified   source=main.go:168

### ISSUE THREAD

**Issue by TanveerMujtaba** [iamseth/oracledb_exporter#88]
We are getting TNS service name error while executing OracleDB_Exporter for an on premise oracle server using Docker, following is the configuration used: 

Docker command: 
docker run -d --name oracledb_exporter  -p 9161:9161 -e DATA_SOURCE_NAME=<UserName>/<Password>@<HostName>:1521/TNSName iamseth/oracledb_exporter

TNSName is in format *.world

Kindly help us to resolve the issue. 

Reagrds
Tanveer Mujtaba K

**Comment by Yannig** [comment]
I think, the string you specify is not valid. Here's an example:

```user/password@//myhost:1521/service```

You can check the string using sqlplus.

**Comment by TanveerMujtaba** [comment]
Hi Yannig 

It worked, thanks for response. Ran into another issue, when I spin a docker container by providing desired details its unable to scrape the data for queries described in default-metrics.toml from Oracle database though it is able to connect to the database. 

I have attached the error screen shot. 

Regards
Tanveer Mujtaba K
