### ISSUE TITLE
Add custom oracle metric/query over external config file

### ISSUE THREAD

**Issue by nkr2001** [iamseth/oracledb_exporter#9]
Hello @iamseth, I appreciate your work, the oracledb_exporter you built is usable. 
It would be really helpful if the oracle sql query would not be hard coded into the exporter.
The exporter would provide much more flexibility if each user could add his custom SQL query and associate a metric name to it over an external config file.
It is not difficult to change the code you provided and add additional query or replace existing ones but it would make more sense to keep the code and the versioning managed by you and the config file with each query/metric separated.
Let me know if you consider improving the oracledb_exporter as I suggested.
Thank you.
K.

**Comment by iamseth** [comment]
I don't have plans to add custom queries however you might be interested in following project which is capable of this.

https://github.com/chop-dbhi/prometheus-sql
