### ISSUE TITLE
[oracledb_exporter 0.2.6a]: error while loading shared libraries: libclntsh.so.18.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by m934030039** [iamseth/oracledb_exporter#92]
Hi Yanning,

I am using your oracledb_exporter 0.2.6a but I got same issue.

https://github.com/iamseth/oracledb_exporter/releases/download/0.2.6a/oracledb_exporter.0.2.6a-ora18.5.linux-amd64.tar.gz

 I am not using Docker but an physical HW server with Oracle 12.2.0 (Red Hat Enterprise Linux Server release 6.9 (Santiago)) 

NOTE: we must use Oracle 12.2.0

I have no clues about how to fix this issue.

[oracledb_exporter.0.2.6a-ora18.5.linux-amd64]# ./oracledb_exporter
./oracledb_exporter: error while loading shared libraries: libclntsh.so.18.1: cannot open shared object file: No such file or directory

[root]#  find / -name libclntsh* -ls 2>/dev/null
-rwxr-xr-x   1 oracle   oinstall  8033199 Jan 26  2017 /home/oracle/database/stage/ext/lib/libclntshcore.so.12.1
 -rwxr-xr-x   1 oracle   oinstall 71638263 Jan 26  2017 /home/oracle/database/stage/ext/lib/libclntsh.so.12.1
-rwxr-x---   1 oracle   oinstall  8033199 Nov 29 10:02 /u01/app/oracle/product/12.2.0/db_1/inventory/Scripts/ext/lib/libclntshcore.so.12.1
 -rwxr-x---   1 oracle   oinstall 71638263 Nov 29 10:02 /u01/app/oracle/product/12.2.0/db_1/inventory/Scripts/ext/lib/libclntsh.so.12.1
-rw-r-----   1 oracle   oinstall  8033199 Nov 29 10:02 /u01/app/oracle/product/12.2.0/db_1/inventory/backup/2019-11-29_10-02-49AM/Scripts/ext/lib/libclntshcore.so.12.1
 -rw-r-----   1 oracle   oinstall 71638263 Nov 29 10:02 /u01/app/oracle/product/12.2.0/db_1/inventory/backup/2019-11-29_10-02-49AM/Scripts/ext/lib/libclntsh.so.12.1
lrwxrwxrwx   1 oracle   oinstall       17 Nov 29 10:05 /u01/app/oracle/product/12.2.0/db_1/lib/libclntsh.so -> libclntsh.so.12.1
-rwxr-xr-x   1 oracle   oinstall  8033625 Nov 29 10:05 /u01/app/oracle/product/12.2.0/db_1/lib/libclntshcore.so.12.1
 -rwxr-xr-x   1 oracle   oinstall 71640177 Nov 29 10:05 /u01/app/oracle/product/12.2.0/db_1/lib/libclntsh.so.12.1
lrwxrwxrwx   1 oracle   oinstall       12 Nov 29 10:04 /u01/app/oracle/product/12.2.0/db_1/lib/libclntsh.so.10.1 -> libclntsh.so
lrwxrwxrwx   1 oracle   oinstall       12 Nov 29 10:04 /u01/app/oracle/product/12.2.0/db_1/lib/libclntsh.so.11.1 -> libclntsh.so
lrwxrwxrwx   1 oracle   oinstall       21 Nov 29 10:05 /u01/app/oracle/product/12.2.0/db_1/lib/libclntshcore.so -> libclntshcore.so.12.1

Many thanks,

-Sheng

**Comment by Yannig** [comment]
This kind of issue have already been talked previously :
- https://github.com/iamseth/oracledb_exporter/issues/61
- https://github.com/iamseth/oracledb_exporter/issues/70
- https://github.com/iamseth/oracledb_exporter/issues/34
