### ISSUE TITLE
error

### ISSUE THREAD

**Issue by alekstass** [iamseth/oracledb_exporter#99]
level=error msg="Unable to convert current value to float (metric=par,metri...in.go:285

This did not happen in 2.3 but happens in 2.6 onwards

**Comment by Yannig** [comment]
Can you try to use debug option in order to get more informations on the statement that trigger this error?

**Comment by alekstass** [comment]
Thank you for a prompt answer - will run in debug mode tomorrow ….
B/R

**Comment by Yannig** [comment]
No new is good news.
